In [4]:
# !pip install pandas

In [6]:
import pandas as pd

In [29]:
train=pd.read_excel('Gen_AI Dataset.xlsx',sheet_name='Train-Set')

In [30]:
train

,Query,Assessment_url
0,I am hiring for Java developers who can also c...,https://www.shl.com/solutions/products/product...
1,I am hiring for Java developers who can also c...,https://www.shl.com/solutions/products/product...
2,I am hiring for Java developers who can also c...,https://www.shl.com/solutions/products/product...
3,I am hiring for Java developers who can also c...,https://www.shl.com/solutions/products/product...
4,I am hiring for Java developers who can also c...,https://www.shl.com/products/product-catalog/v...
...,...,...
60,I want to hire a Senior Data Analyst with 5 ye...,https://www.shl.com/solutions/products/product...
61,I want to hire a Senior Data Analyst with 5 ye...,https://www.shl.com/solutions/products/product...
62,I want to hire a Senior Data Analyst with 5 ye...,https://www.shl.com/solutions/products/product...
63,I want to hire a Senior Data Analyst with 5 ye...,https://www.shl.com/solutions/products/product...
64,I want to hire a Senior Data Analyst with 5 ye...,https://www.shl.com/solutions/products/product...

In [20]:
train.drop_duplicates(subset='Query')

,Query,Assessment_url
0,I am hiring for Java developers who can also c...,https://www.shl.com/solutions/products/product...
5,I want to hire new graduates for a sales role ...,https://www.shl.com/solutions/products/product...
14,I am looking for a COO for my company in China...,https://www.shl.com/products/product-catalog/v...
20,KEY RESPONSIBITILES:\n\nManage the sound-scape...,https://www.shl.com/solutions/products/product...
25,"Content Writer required, expert in English and...",https://www.shl.com/products/product-catalog/v...
30,Find me 1 hour long assesment for the below jo...,https://www.shl.com/solutions/products/product...
39,"ICICI Bank Assistant Admin, Experience require...",https://www.shl.com/solutions/products/product...
45,We're looking for a Marketing Manager who can ...,https://www.shl.com/solutions/products/product...
50,Based on the JD below recommend me assessment ...,https://www.shl.com/solutions/products/product...
55,I want to hire a Senior Data Analyst with 5 ye...,https://www.shl.com/solutions/products/product...

In [22]:
ground_truth = {}
for _, row in train.iterrows():
    query = row['Query']
    if query not in ground_truth:
        ground_truth[query] = []
    ground_truth[query].append(row['Assessment_url'])

In [23]:
ground_truth

{'I am hiring for Java developers who can also collaborate effectively with my business teams. Looking for an assessment(s) that can be completed in 40 minutes.': ['https://www.shl.com/solutions/products/product-catalog/view/automata-fix-new/',
  'https://www.shl.com/solutions/products/product-catalog/view/core-java-entry-level-new/',
  'https://www.shl.com/solutions/products/product-catalog/view/java-8-new/',
  'https://www.shl.com/solutions/products/product-catalog/view/core-java-advanced-level-new/',
  'https://www.shl.com/products/product-catalog/view/interpersonal-communications/'],
 'I want to hire new graduates for a sales role in my company, the budget is for about an hour for each test. Give me some options': ['https://www.shl.com/solutions/products/product-catalog/view/entry-level-sales-7-1/',
  'https://www.shl.com/solutions/products/product-catalog/view/entry-level-sales-sift-out-7-1/',
  'https://www.shl.com/solutions/products/product-catalog/view/entry-level-sales-solution/',
  'https://www.shl.com/solutions/products/product-catalog/view/sales-representative-solution/',
  'https://www.shl.com/products/product-catalog/view/business-communication-adaptive/',
  'https://www.shl.com/solutions/products/product-catalog/view/technical-sales-associate-solution/',
  'https://www.shl.com/solutions/products/product-catalog/view/svar-spoken-english-indian-accent-new/',
  'https://www.shl.com/products/product-catalog/view/interpersonal-communications/',
  'https://www.shl.com/solutions/products/product-catalog/view/english-comprehension-new/'],
 'I am looking for a COO for my company in China and I want to see if they are culturally a right fit for our company. Suggest me an assessment that they can complete in about an hour': ['https://www.shl.com/products/product-catalog/view/enterprise-leadership-report/',
  'https://www.shl.com/products/product-catalog/view/occupational-personality-questionnaire-opq32r/',
  'https://www.shl.com/solutions/products/product-catalog/view/opq-leadership-report/',
  'https://www.shl.com/solutions/products/product-catalog/view/opq-team-types-and-leadership-styles-report',
  'https://www.shl.com/products/product-catalog/view/enterprise-leadership-report-2-0/',
  'https://www.shl.com/solutions/products/product-catalog/view/global-skills-assessment/'],
 'KEY RESPONSIBITILES:\n\nManage the sound-scape of the station through appropriate creative and marketing interventions to Increase or Maintain the listenership\nActs as an interface between Programming & sales team, thereby supporting the sales team by providing creative inputs in order to increase the overall ad spends by clients\nBuild brand Mirchi by ideating fresh programming initiatives on air campaigns, programming led on-ground events & new properties to ensure brand differentiation & thus increase brand recall at station level\nInvest time in local RJs to grow & develop them as local celebrities\nThrough strong networking, must focus on identifying the best of local talent and ensure to bring the creative minds from the market on board with Mirchi\nBuild radio as a category for both listeners & advertisers\nPeople Management\nIdentifying the right talent and investing time in developing them by frequent feedback on their performance\nMonitor, Coach and mentor team members on a regular basis\nDevelopment of Jocks as per guidelines\nMust have an eye to spot the local talent to fill up vacancies locally\n\n\n\n\nTECHNICAL SKILLS & QUALIFICATION REQUIRED:\n\nGraduation / Post Graduation (Any specialisation) with 8 -12 years of relevant experience\nExperience in digital content conceptualisation\nStrong branding focus\nMust be well-read in variety of areas and must keep up with the latest events in the city / cluster / country\nMust know to read, write & speak English \n\n\nPERSONAL ATTRIBUTES:\n\nExcellent communication skills\nGood interpersonal skills\nPeople management\n\n\nSuggest me some tests for the above jd. The duration should be at most 90 mins': ['https://www.shl.com/solutions/products/product-catalog/view/verify-verbal-ability-next-generation/',
  'https://www.shl.com/solutions/products/product-catalog/view/shl-verify-interactive-inductive-reasoning/',
  'https://www.shl.com/solutions/products/product-catalog/view/marketing-new/',
  'https://www.shl.com/solutions/products/product-catalog/view/english-comprehension-new/',
  'https://www.shl.com/products/product-catalog/view/interpersonal-communications/'],
 'Content Writer required, expert in English and SEO.': ['https://www.shl.com/products/product-catalog/view/english-comprehension-new/',
  'https://www.shl.com/solutions/products/product-catalog/view/drupal-new/',
  'https://www.shl.com/solutions/products/product-catalog/view/written-english-v1/',
  'https://www.shl.com/solutions/products/product-catalog/view/occupational-personality-questionnaire-opq32r/',
  'https://www.shl.com/solutions/products/product-catalog/view/search-engine-optimization-new/'],
 'Find me 1 hour long assesment for the below job at SHL\nJob Description\n\n Join a community that is shaping the future of work! SHL, People Science. People Answers. \n\nAre you a seasoned QA Engineer with a flair for innovation? Are you ready to shape the future of talent assessment and empower organizations to unlock their full potential? If so, we want you to be a part of the SHL Team! As a QA Engineer, you will be involved in creating and implementing software solutions that contribute to the development of our ground-breaking products.\n\nAn excellent benefit package is offered in a culture where career development, with ongoing manager guidance, collaboration, flexibility, diversity, and inclusivity are all intrinsic to our culture.\u202f There is a huge investment in SHL currently so there’s no better time to become a part of something transformational.\n\nWhat You Will Be Doing\n\n Getting involved in engineering quality assurance and providing inputs when required. \n Create and develop test plans for various forms of testing. \n Conducts and/or participates in formal and informal test case reviews. \n Develop and initiate functional tests and regression tests. \n Rolling out improvements for testing and quality processes. \n\nEssential\n\n What we are looking for from you: \n\n Development experience – Java or JavaScript, CSS, HTML (Automation) \n Selenium WebDriver and page object design pattern (Automation) \n SQL server knowledge \n Test case management experience. \n Manual Testing \n\nDesirable\n\n Knowledge the basic concepts of testing \n Strong solution-finding experience \n Strong verbal and written communicator. \n\nGet In Touch\n\nFind out how this one-off opportunity can help you achieve your career goals by making an application to our knowledgeable and friendly Talent Acquisition team. Choose a new path with SHL.\n\n #CareersAtSHL #SHLHiringTalent \n\n#TechnologyJobs #QualityAssuranceJobs\n\n#CareerOpportunities #JobOpportunities \n\nAbout Us\n\nWe unlock the possibilities of businesses through the power of people, science and technology.\nWe started this industry of people insight more than 40 years ago and continue to lead the market with powerhouse product launches, ground-breaking science and business transformation.\nWhen you inspire and transform people’s lives, you will experience the greatest business outcomes possible. SHL’s products insights, experiences, and services can help achieve growth at scale.\n\nWhat SHL Can Offer You\n\nDiversity, equity, inclusion and accessibility are key threads in the fabric of SHL’s business and culture (find out more about DEI and accessibility at SHL )\nEmployee benefits package that takes care of you and your family.\nSupport, coaching, and on-the-job development to achieve career success\nA fun and flexible workplace where you’ll be inspired to do your best work (find out more LifeAtSHL )\nThe ability to transform workplaces around the world for others.\n\nSHL is an equal opportunity employer. We support and encourage applications from a diverse range of candidates. We can, and do make adjustments to make sure our recruitment process is as inclusive as possible.\n\nSHL is an equal opportunity employer.': ['https://www.shl.com/solutions/products/product-catalog/view/automata-selenium/',
  'https://www.shl.com/products/product-catalog/view/professional-7-1-solution/',
  'https://www.shl.com/solutions/products/product-catalog/view/javascript-new/',
  'https://www.shl.com/solutions/products/product-catalog/view/htmlcss-new/',
  'https://www.shl.com/solutions/products/product-catalog/view/css3-new/',
  'https://www.shl.com/solutions/products/product-catalog/view/selenium-new/',
  'https://www.shl.com/solutions/products/product-catalog/view/sql-server-new/',
  'https://www.shl.com/solutions/products/product-catalog/view/automata-sql-new/',
  'https://www.shl.com/solutions/products/product-catalog/view/manual-testing-new/'],
 'ICICI Bank Assistant Admin, Experience required 0-2 years, test should be 30-40 mins long': ['https://www.shl.com/solutions/products/product-catalog/view/administrative-professional-short-form/',
  'https://www.shl.com/solutions/products/product-catalog/view/verify-numerical-ability/',
  'https://www.shl.com/solutions/products/product-catalog/view/financial-professional-short-form/',
  'https://www.shl.com/solutions/products/product-catalog/view/bank-administrative-assistant-short-form/',
  'https://www.shl.com/solutions/products/product-catalog/view/general-entry-level-data-entry-7-0-solution/',
  'https://www.shl.com/solutions/products/product-catalog/view/basic-computer-literacy-windows-10-new/'],
 "We're looking for a Marketing Manager who can drive Recro’s brand positioning, community growth, and overall marketing strategy to fuel business growth. The ideal candidate is a strategic thinker, an execution-focused leader, and an expert in building high-performing marketing teams.\n\n\n\nAbout Recro \n\n\nRecro is a developer-focused platform that was founded to match individual expertise with the right opportunities seamlessly. We empower talented developers by providing them with relevant experience at fast-growing startups based on technical competencies and aspirations. These opportunities have a significant impact on their career success and help them become their best self.\n\n\nAbout The Role\n\nDevelop and execute Recro’s marketing strategy to enhance community engagement, brand positioning, and industry presence.\nLead the marketing team and oversee all functions, with a strong focus on community building, events, brand positioning, social media engagement, and market intelligence.\nDrive demand generation by leveraging community-driven initiatives, influencer partnerships, and strategic event participation.\nOrganize and represent Recro at industry conferences, networking events, and developer meetups to strengthen brand positioning.\nBuild and nurture relationships with industry influencers, developer communities, and partners to create brand advocates.\nOwn the marketing funnel, ensuring continuous tracking, analysis, and optimization of community engagement and event performance.\nCollaborate with sales, business development, and leadership teams to align marketing strategies with business objectives and market trends.\nManage marketing budgets, prioritizing event sponsorships, partnerships, and community-driven growth initiatives.\nDevelop compelling content strategies to drive community interaction and thought leadership.\nStay ahead of industry trends, competitor movements, and emerging social and market intelligence to maintain a competitive edge\n\n\nRequirements\n\n5+ years of experience in B2B marketing with a strong focus on community building, events, and brand positioning.\nHas a deep understanding how demand generation works from traditional and new age channels\nProven track record of executing large-scale events and community-driven initiatives.\nExperience in developing partnerships with industry influencers and thought leaders.\nStrong understanding of social media dynamics and community engagement strategies.\nAbility to leverage market intelligence and competitor insights to refine marketing strategies.\nExceptional storytelling and brand communication skills.\nHands-on experience with event management, sponsorships, and partnership collaborations.\nExperience in building a thriving developer or tech community is a plus.\nOpen for flexible work timings as per target geographies.\n\nI have no bar on duration.": ['https://www.shl.com/solutions/products/product-catalog/view/manager-8-0-jfa-4310/',
  'https://www.shl.com/solutions/products/product-catalog/view/microsoft-excel-365-essentials-new/',
  'https://www.shl.com/solutions/products/product-catalog/view/digital-advertising-new/',
  'https://www.shl.com/solutions/products/product-catalog/view/shl-verify-interactive-inductive-reasoning/',
  'https://www.shl.com/solutions/products/product-catalog/view/writex-email-writing-sales-new/'],
 'Based on the JD below recommend me assessment for the Consultant position in my organizations. The assessment should not be more than 90 mins\nb Description\n\n Job Purpose \n\nResponsibilities\n\nThe Consultant role supports the broader professional services organization by leading the delivery of impactful client solutions and advising on client programs. Consultants are expected to deliver solutions, services, and insights that are driven by industry best practices and that positively impact client business objectives and partnerships. Individuals in this role provide I/O technical guidance to internal and external stakeholders, and drive continuous improvement related to project delivery.  Primary Duties and Responsibilities  Primary job duties and responsibilities include but may not be limited to:\n\n Planning, executing, and documenting projects related to clients’ talent assessment and development needs (e.g., job analysis, validation, leadership assessment, succession planning, program implementation, adverse impact analyses, best practices). \n Leading projects; ensuring overall quality for all client deliverables and guiding other to do the same. \n Serving as an expert resource to clients and internal stakeholders about issues related to talent assessment, selection, and development. \n Linking human capital insights to business outcomes and demonstrating ROI. \n Collaborating with members of the Sales team to manage existing programs and identify new business opportunities. \n Maintaining up-to-date knowledge of the field including empirical research, industry trends, and competitors. \n Providing talent analytics and data insights to technical and non-technical stakeholders. \n Contributing to the ongoing definition and development of SHL’s offerings and methodologies. \n Presenting to and interacting with senior client stakeholders. \n Providing thought leadership; working with delivery and commercial teams to drive improvements in the scoping and execution of projects/deliverables. \n\n Key Competencies: \n\n Decision Making \n Collaboration \n Building Relationships \n Creativity and Innovation \n Planning and Organizing \n Delivering Results \n Adaptability \n\n Qualifications include: \n\n A graduate degree in Industrial/Organizational psychology or a related discipline \n 2+ years of relevant work experience in applied talent assessment, talent management, or employee selection, including program design and implementation \n Client-facing delivery experience with design and implementation of talent assessment programs (including job analysis, criterion validation, content validation, and interviews) \n Selection system development and / or evaluation \n Proficient in at least one statistical program (e.g., SPSS, R) \n Strong communication skills and presenting technical results to non-technical stakeholders \n\n#IO #IndustrialPsychology #psychtalent #talentmanagement #talentassessment #psychometrics #consultant\n\nAbout Us\n\nWe unlock the possibilities of businesses through the power of people, science, and technology.\n\nWe started this industry of people insight more than 40 years ago and continue to lead the market with powerhouse product launches, ground-breaking science, and business transformation.\n\nWhen you inspire and transform people’s lives, you will experience the greatest business outcomes possible. SHL’s products insights, experiences, and services can help achieve growth at scale.\n\nMore at shl.com.\n\nWhat SHL Can Offer You\n\n An inclusive culture. \n A fun and flexible workplace where you’ll be inspired to do your best work. \n Employee benefits package that takes care of you and your family. \n Support, coaching, and on-the-job development to achieve career success. \n The ability to transform workplaces around the world for others. \n\nSHL is an equal opportunity employer.': ['https://www.shl.com/solutions/products/product-catalog/view/shl-verify-interactive-numerical-calculation/',
  'https://www.shl.com/solutions/products/product-catalog/view/administrative-professional-short-form/',
  'https://www.shl.com/solutions/products/product-catalog/view/verify-verbal-ability-next-generation/',
  'https://www.shl.com/products/product-catalog/view/occupational-personality-questionnaire-opq32r/',
  'https://www.shl.com/solutions/products/product-catalog/view/professional-7-1-solution/'],
 'I want to hire a Senior Data Analyst with 5 years of experience and expertise in SQL, Excel and Python. The assessment can be 1-2 hour long': ['https://www.shl.com/solutions/products/product-catalog/view/sql-server-analysis-services-%28ssas%29-%28new%29/',
  'https://www.shl.com/solutions/products/product-catalog/view/sql-server-new/',
  'https://www.shl.com/solutions/products/product-catalog/view/automata-sql-new/',
  'https://www.shl.com/solutions/products/product-catalog/view/python-new/',
  'https://www.shl.com/solutions/products/product-catalog/view/tableau-new/',
  'https://www.shl.com/solutions/products/product-catalog/view/microsoft-excel-365-new/',
  'https://www.shl.com/solutions/products/product-catalog/view/microsoft-excel-365-essentials-new/',
  'https://www.shl.com/solutions/products/product-catalog/view/professional-7-0-solution-3958/',
  'https://www.shl.com/solutions/products/product-catalog/view/professional-7-1-solution/',
  'https://www.shl.com/solutions/products/product-catalog/view/data-warehousing-concepts/']}

In [24]:
from google import genai
client = genai.Client()
for model in client.models.list():
    print(model.name)

models/gemini-2.5-flash
models/gemini-2.5-pro
models/gemini-2.0-flash
models/gemini-2.0-flash-001
models/gemini-2.0-flash-exp-image-generation
models/gemini-2.0-flash-lite-001
models/gemini-2.0-flash-lite
models/gemini-2.5-flash-preview-tts
models/gemini-2.5-pro-preview-tts
models/gemma-3-1b-it
models/gemma-3-4b-it
models/gemma-3-12b-it
models/gemma-3-27b-it
models/gemma-3n-e4b-it
models/gemma-3n-e2b-it
models/gemini-flash-latest
models/gemini-flash-lite-latest
models/gemini-pro-latest
models/gemini-2.5-flash-lite
models/gemini-2.5-flash-image
models/gemini-2.5-flash-lite-preview-09-2025
models/gemini-3-pro-preview
models/gemini-3-flash-preview
models/gemini-3.1-pro-preview
models/gemini-3.1-pro-preview-customtools
models/gemini-3.1-flash-lite-preview
models/gemini-3-pro-image-preview
models/nano-banana-pro-preview
models/gemini-3.1-flash-image-preview
models/gemini-robotics-er-1.5-preview
models/gemini-2.5-computer-use-preview-10-2025
models/deep-research-pro-preview-12-2025
models/gemini-embedding-001
models/aqa
models/imagen-4.0-generate-001
models/imagen-4.0-ultra-generate-001
models/imagen-4.0-fast-generate-001
models/veo-2.0-generate-001
models/veo-3.0-generate-001
models/veo-3.0-fast-generate-001
models/veo-3.1-generate-preview
models/veo-3.1-fast-generate-preview
models/gemini-2.5-flash-native-audio-latest
models/gemini-2.5-flash-native-audio-preview-09-2025
models/gemini-2.5-flash-native-audio-preview-12-2025

In [27]:
from langchain_google_genai import GoogleGenerativeAIEmbeddings,ChatGoogleGenerativeAI
llm = ChatGoogleGenerativeAI(
    model="gemini-3-flash-preview",
    temperature=0.3,    # low temperature for factual, consistent recommendations
)

In [28]:
llm.invoke("hello")

KeyboardInterrupt:

In [31]:
import json
with open("shl_llm_documents.json","r",encoding="utf-8") as f:   
    all_info=json.load(f)

In [33]:
len(all_info)

377

In [35]:
test=pd.read_excel('Gen_AI Dataset.xlsx',sheet_name='Test-Set')

In [36]:
test

                                               Query
0  Looking to hire mid-level professionals who ar...
1  Job Description\n\n Join a community that is s...
2  I am hiring for an analyst and wants applicati...
3  I have a JD Job Description\n\n People Science...
4  I am new looking for new graduates in my sales...
5  For Marketing - Content Writer Position\n\nDep...
6  I want to hire a product manager with 3-4 year...
7  Suggest me an assessment for the JD below Job ...
8  I want to hire Customer support executives who...

In [37]:
queries=test['Query'].tolist()

In [38]:
queries

['Looking to hire mid-level professionals who are proficient in Python, SQL and Java Script. Need an assessment package that can test all skills with max duration of 60 minutes.',
 'Job Description\n\n Join a community that is shaping the future of work! \n\n SHL, People Science. People Answers. \n\nAre you an AI enthusiastwith visionary thinking to conceptualize AI-based products? Are you looking to apply these skills in an environment where teamwork and collaboration are key to developing our digital product experiences? We are seeking a Research Engineer to join our team to deliver robust AI/ML models. You will closely work with the product team to spot opportunities to use AI in the current product stack and influence the product roadmap by incorporating AI-led features/products.\n\nAn excellent benefits package is offered in a culture where career development, with ongoing manager guidance, collaboration, flexibility, diversity, and inclusivity are all intrinsic to our culture.\u202f There is a huge investment in SHL currently so there’s no better time to become a part of something transformational.\n\nWhat You Will Be Doing\n\n Develop and experiment with machine learning models like NLP, computer vision etc. \n Prototype and fine-tune generative AI models for text, image, speech, and video generation. \n Implement emerging LLM technologies and monitoring tools. \n Manage the entire AI/ML lifecycle from research to deployment and maintenance. \n Optimize models for scalability, efficiency, and performance. \n Collaborate with ML engineers for solution delivery and propose AI-driven enhancements. \n Contribute to research, documentation, and publications with AI/ML advancements. \n\nEssential\n\nWhat we are looking for from you:\n\n Relevant experience in AI/ML - NLP, speech processing, and computer vision. \n Proficiency in Python and ML frameworks such as TensorFlow, PyTorch, & OpenAI APIs. \n Good knowledge of ML theory deep learning, and statistical modeling. \n\nDesirable\n\n Familiarity with Generative AI (LLMs & RAG). \n Experience in prototyping and deploying AI. \n Agile and proactive thinking. \n\nGet In Touch\n\nFind out how this one-off opportunity can help you to achieve your career goals by making an application to our knowledgeable and friendly Talent Acquisition team. Choose a new path with SHL.\n\n #CareersAtSHL #SHLHiringTalent \n\n#AIJobs #ResearchJobs #MLJobs\n\n#CareerOpportunities #JobOpportunities \n\nAbout Us\n\n We unlock the possibilities of businesses through the power of people, science and technology. \n We started this industry of people insight more than 40 years ago and continue to lead the market with powerhouse product launches, ground-breaking science and business transformation. \n When you inspire and transform people’s lives, you will experience the greatest business outcomes possible. SHL’s products insights, experiences, and services can help achieve growth at scale. \n\nWhat SHL Can Offer You\n\n Diversity, equity, inclusion and accessibility are key threads in the fabric of SHL’s business and culture (find out more about DEI and accessibility at SHL ) \n Employee benefits package that takes care of you and your family. \n Support, coaching, and on-the-job development to achieve career success \n A fun and flexible workplace where you’ll be inspired to do your best work (find out more LifeAtSHL ) \n The ability to transform workplaces around the world for others. \n\nSHL is an equal opportunity employer. We support and encourage applications from a diverse range of candidates. We can, and do make adjustments to make sure our recruitment process is as inclusive as possible.\n\nCan you recommend some assessment that can help me screen applications. Time limit is less than 30 minutes',
 'I am hiring for an analyst and wants applications to screen using Cognitive and personality tests, what options are available within 45 mins.',
 'I have a JD Job Description\n\n People Science. People Answers  !\n\nDo you love contributing to commercial growth and success? Join as a Presales Specialist! In this role, you’ll support the Presales function and commercial teams by building custom client demos, developing RFP responses, writing high quality Statements of Work, ensuring our deals are appropriately scoped and priced.\n\nAn excellent benefits package is offered in a culture where career development, with ongoing manager guidance, collaboration, flexibility, diversity and inclusivity are all intrinsic to our culture. There is a huge investment in SHL currently so there ’ s no better time to become a part of something transformational. Hybrid working is available\n\nThis role is based in the US. Candidates must be eligible to work in the US without sponsorship. SHL does not offer visa sponsorship.\n\nThe Presales Specialist is responsible for creating, curating, and presenting compelling content to support the Solution Architects and Sales team during the presales phase. This includes:\n\n Building custom demos \n Responding to RFPs \n Maintaining knowledge of SHL commercial offerings, pricing, and platforms. \n Scoping support for commercial opportunities \n Creating compelling proposals \n Presenting Solution Vision to Customers \n Ensuring successful handover from pre-sales to delivery teams \n Maintaining domain expertise in the Talent Intelligence and HCM space \n\nKey Responsibilities\n\n Content Creation and Customization: \n\n Develop customized content, including proposal (RFI/RFP) presentations, product demos and Word/Excel proposals, to support the presales process. \n Create engaging content that clearly communicates the value proposition of SHL’s solutions and services \n Collaborate with Solution Architects and sales teams to ensure content aligns with client requirements, business goals, strategy \n\n Collaboration with Sales and Technical (CoE) Teams: \n\n Work closely with Centre of Excellence to understand client technical requirements and submission planning. \n Professional Services: be an expert on what products and services we deliver. Ensure all aspects of client engagements can be delivered and set realistic timelines \n Product: Allowing a solid understanding of our solutions and stay appraised of digital roadmap and releases \n\nCustomer Engagement\n\n Support sales teams getting ready for client meetings, demos, and presentations \n Help refine product positioning and messaging to resonate with the client’s industry and business context. \n\nContent Strategy And Development\n\n Develop and maintain a local library of reusable content, templates, and resources for presales presentations, proposals, and client demos. \n Continuously assess the effectiveness of content and iterate based on client feedback and sales outcomes. \n Stay up to date with industry trends, competitor content, and customer preferences to enhance content quality \n\n Required Skills and Qualifications: \n\n Qualification in Technology, Marketing, Communications, Business, or a related field \n Ideally 2-4 years of experience in a Presales or commercial operations preferably within a technology, SaaS or services industry. \n Strong writing, editing, and presentation skills with an ability to craft clear, persuasive, and engaging content. \n Experience with design tools (e.g., PowerPoint, Synthesia, Adobe, Canva). \n Strong communication and collaboration skills to work cross-functional teams. \n Ability to quickly understand customer needs and develop content that resonates with different audiences. \n Attention to detail and ability to manage multiple content development projects simultaneously. \n Utility player! You thrive in the unknown and enjoy wearing multiple hats \n\nDesirable\n\n Presales tools: Walnut, Custom Report Developer tools \n Marketing skills: Canva, Synthesia \n Contracting skills: Experience writing Statements of work \n Proposal skills: populating responses to RFPs, Loopio \n Technical skills: understanding of HR technology and workflows. Experience solutioning complex integrations. \n\nGet In Touch\n\nFind out how this one-off opportunity can help you to achieve your career goals by making an application to our knowledgeable Talent Acquisition team. Choose a new path with SHL. \n\n#PreSalesOperations #SHL #CareersAtSHL \n\nAbout Us\n\nWe unlock the possibilities of businesses through the power of people, science and technology.\nWe started this industry of people insight more than 40 years ago and continue to lead the market with powerhouse product launches, ground-breaking science and business transformation.\nWhen you inspire and transform people’s lives, you will experience the greatest business outcomes possible. SHL’s products insights, experiences, and services can help achieve growth at scale.\n\nWhat SHL Can Offer You\n\nDiversity, equity, inclusion and accessibility are key threads in the fabric of SHL’s business and culture (find out more about DEI and accessibility at SHL )\n\nEmployee benefits package that takes care of you and your family.\nSupport, coaching, and on-the-job development to achieve career success\nA fun and flexible workplace where you’ll be inspired to do your best work (find out more LifeAtSHL )\nThe ability to transform workplaces around the world for others.\n\nSHL is an equal opportunity employer. We support and encourage applications from a diverse range of candidates. We can, and do make adjustments to make sure our recruitment process is as inclusive as possible.\n\nHere and I have want them to give a test which is atleast  30 mins long',
 'I am new looking for new graduates in my sales team, suggest an 30 min long assessment',
 "For Marketing - Content Writer Position\n\nDepartment: Marketing\n\nLocation: Gurugram\n\nAbout Company\n\nShopClues.com is India's leading e-commerce platform that is focused on changing the shopping scenario of the country. We are the one-stop platform for everything from electronics to fashion to home & kitchen. The company visions to be the largest and most customer-centric e-commerce platform for India.\n\nShopClues.com has been operating out of Silicon Valley since February 2011 and has its headquarters in Gurugram. The Company launched its Beta version on 26th January 2012 and has been constantly evolving since then for the better.\n\nOur Culture\n\nWe are a team of enthusiastic and determined individuals, who believe in working together with lots of energy, bringing continuous innovations to the organization, and celebrating every bit of it. We provide equal opportunity to each individual and look forward to executing the best ideas.\n\nThe Typical Creative Process Involves\n\nDiscussing the campaign's core message and target audience\nBrainstorming visual and copy ideas with other members of the creative team\nVisualizing different forms of communication approaches for various marketing platforms like Website, Email, Social, etc. for ShopClues.\nGenerating Stories for Brands core blog, and other content-driven platforms.\nOverseeing the production phase till the final output.\nExperience in the publishing of Push Notification and unique Product Description.",
 'I want to hire a product manager with 3-4 years of work experience and expertise in SDLC, Jira and Confluence',
 'Suggest me an assessment for the JD below Job Description\n\n Find purpose in each day while contributing to a workplace revolution! SHL, People Science. People Answers. \n\nAre you a driven business professional eager to develop your career by contributing directly to business success? SHL is seeking a Finance & Operations Analyst to join our AMS team!\n\n The Finance & Operations Analyst  will provide insights, analysis, and guidance to commercial teams to drive informed outcomes. This role bridges the gap between finance & operations and the business, ensuring alignment with the organization’s strategic goals and delivering value-added advice to improve performance.\n\nAn excellent benefits package is offered in a culture where career development, with ongoing manager guidance, collaboration, flexibility, diversity and inclusivity are all intrinsic to our culture.\u202f There is a huge investment in SHL currently so there’s no better time to become a part of something transformational.\u202f Hybrid working is available.\n\nWhat You Will Be Doing\n\n Financial Reporting: Deliver accurate monthly management accounts, variance evaluation, and KPI insights to help data-driven decision-making. \n Budgeting & Forecasting: Assist in preparing budgets and forecasts, identifying financial risks, opportunities, and recommending strategic actions. \n Business Partnering: Act as the primary finance contact, collaborating with sales, marketing, and operations on pricing, investments, and business cases. \n Cost Management: Monitor and evaluate costs, ensuring budget alignment and identifying cost-saving opportunities without compromising service quality. \n Performance Insights: Track financial KPIs, providing actionable insights to enhance business performance and profitability. \n Process Improvement: Streamline financial processes, implement top practices, and guidance system enhancements for efficiency and accuracy. \n Ad-Hoc Analysis : Provide financial insights to assist business initiatives, projects, and outcomes. Assist senior finance team members with reporting, insight, and financial planning. \n\n What we are looking for from you: \n\n Experience in finance, accounting, business, or a related field. \n 1-2 years of experience in a financial, analytical, or commercial role. \n Experience in financial modeling, Excel, and accounting systems (e.g., SAP, Oracle, or similar). \n Knowledge of commercial operations and drivers of profitability. \n Strong analytical and critical thinking techniques with attention to detail. \n Excellent relationship-building and communication techniques, able to present financial data clearly to non-finance stakeholders. \n Proactive and self-motivated, with a collaborative approach to work. \n\nGet In Touch\n\nFind out how this one-off opportunity can help you to achieve your career goals by making an application to our knowledgeable and friendly Talent Acquisition team. Choose a new path with SHL.\n\n #CareersAtSHL #SHLHiringTalent #HybridRole # salesoperationsjobs #financeanalystjobs #salesjobs\n\nAbout Us\n\nWe unlock the possibilities of businesses through the power of people, science and technology.\nWe started this industry of people insight more than 40 years ago and continue to lead the market with powerhouse product launches, ground-breaking science and business transformation.\nWhen you inspire and transform people’s lives, you will experience the greatest business outcomes possible. SHL’s products insights, experiences, and services can help achieve growth at scale.\n\nWhat SHL Can Offer You\n\nDiversity, equity, inclusion and accessibility are key threads in the fabric of SHL’s business and culture (find out more about DEI and accessibility at SHL )\n\nEmployee benefits package that takes care of you and your family.\nSupport, coaching, and on-the-job development to achieve career success\nA fun and flexible workplace where you’ll be inspired to do your best work (find out more LifeAtSHL )\nThe ability to transform workplaces around the world for others.\n\nSHL is an equal opportunity employer. We support and encourage applications from a diverse range of candidates. We can, and do make adjustments to make sure our recruitment process is as inclusive as possible.',
 'I want to hire Customer support executives who are expert in English communication.  \nWe are looking for talented Customer Support specialists to join our Product operations team in India (Mumbai)\n\n\nMinna connects global banks and fintech with subscription businesses to give consumers self-serve subscription management in-app. Minna is a technology partner to top-tier financial institutions, fintech and subscription businesses, providing subscription management functionality for 50+ million banking and fintech customers across the United States, United Kingdom and Europe.\nMinna builds the infrastructure that links Subscription Merchants (such as Netflix, Spotify, Amazon) to leading Financial Institutions (Lloyds Bank, ING Belgium, Swedbank to name a few). This connection enables consumers to effortlessly manage their subscriptions by performing actions like canceling, pausing, or changing their plans.\n\n\nResponsibilities:\n\nEfficiently manage cancellations and monitor cancellation status for merchants\nInitiate and execute workflows for cancellations at various stages of the cancellation journey with merchants\nProvide friendly and efficient customer service support via chat, calls, emails, and other channels\nFamiliarity with Minna’s Merchant Registry and classifications for merchants, services, and categories\nProficiency in understanding subscription terms and pulling relevant information from internal systems to support Account Management, Sales, and other queries\nConduct outbound calls to customers for subscription management and issue resolution\nHandle incoming queries from customers and merchants, ensuring timely resolution and escalation when necessary\nCollaborate with cross-functional teams to improve processes and enhance the customer experience\nMaintain accurate records and documentation of customer interactions and issue resolutions\n\n\nBased\n\nThis role is based in Mumbai and will require daily commute.\n\n\nRequirements:\n\nFluent in English with a minimum of 2-3 years of work experience in an International Call Center (US Voice Process or UK Voice Process)\nComfortable working full-time in English and willing to work in US or UK shifts, must be flexible with work timings.\nDemonstrated ability to deliver excellent customer service and resolve issues with good judgment\nStrong analytical abilities for troubleshooting and problem-solving\nAppreciation for routine tasks and ability to follow clear instructions\nComfortable multitasking to manage calls, emails, and chats simultaneously in an outbound calling process\nStrong communication skills, both verbal and written, with a friendly and professional tone\nAbility to adapt to a fast-paced and technologically advanced environment\nDetail-oriented with strong organizational skills and the ability to prioritize tasks effectively\n\n\nOur global benefits\n\n25 days holiday plus public holidays\nPrivate health insurance\nSubscription allowance\nFind more information about our benefits here\nMinna is an equal opportunities employer and does not discriminate on the basis of race, nationality, ethnicity, skin colour, religion, disability or sexual orientation. We celebrate and embrace a diverse workforce and are committed to building a team that represents a variety of backgrounds, perspectives and skills.']

In [39]:
results=[]

In [65]:
import requests
import json

API_URL = "http://localhost:8000/recommend" # change to your Render URL

def recommend(query: str) -> dict:
    response = requests.post(API_URL, json={"query": query})
    response.raise_for_status()
    return response.json()

def display_results(result: dict):
    print(f"Query: {result['query']}\n")
    print(f"Reasoning: {result['reasoning']}\n")
    print(f"{'─' * 60}")
    
    for i, rec in enumerate(result['recommendations'], start=1):
        print(f"\n[{i}] {rec['title']}")
        print(f"  URL:               {rec['url']}")
        print(f"  Description:       {rec['description']}")
        print(f"  Job Levels:        {', '.join(rec['job_levels'])}")
        print(f"  Languages:         {', '.join(rec['languages'])}")
        print(f"  Assessment Length: {rec['assessment_length']}")
        print(f"  Test Types:        {', '.join(rec['test_types'])}")
        print(f"  Remote Testing:    {rec['remote_testing']}")
        print(f"  Adaptive/IRT:      {rec['adaptive_irt']}")
        # print(f"  Relevance Score:   {rec['relevance_score']}")
        print(f"  Why it fits:       {rec['relevance_reason']}")

# ── Run a query ───────────────────────────────────────────────

# query = "I am hiring for Java developers who can also collaborate effectively with my business teams. Looking for an assessment that can be completed in 40 minutes."


# for query in queries[-]:
query=queries[-3]
print(query)
result = recommend(query)
results.append(result)
    # display_results(result)

I want to hire a product manager with 3-4 years of work experience and expertise in SDLC, Jira and Confluence

In [45]:
queries[-2:]

['Suggest me an assessment for the JD below Job Description\n\n Find purpose in each day while contributing to a workplace revolution! SHL, People Science. People Answers. \n\nAre you a driven business professional eager to develop your career by contributing directly to business success? SHL is seeking a Finance & Operations Analyst to join our AMS team!\n\n The Finance & Operations Analyst  will provide insights, analysis, and guidance to commercial teams to drive informed outcomes. This role bridges the gap between finance & operations and the business, ensuring alignment with the organization’s strategic goals and delivering value-added advice to improve performance.\n\nAn excellent benefits package is offered in a culture where career development, with ongoing manager guidance, collaboration, flexibility, diversity and inclusivity are all intrinsic to our culture.\u202f There is a huge investment in SHL currently so there’s no better time to become a part of something transformational.\u202f Hybrid working is available.\n\nWhat You Will Be Doing\n\n Financial Reporting: Deliver accurate monthly management accounts, variance evaluation, and KPI insights to help data-driven decision-making. \n Budgeting & Forecasting: Assist in preparing budgets and forecasts, identifying financial risks, opportunities, and recommending strategic actions. \n Business Partnering: Act as the primary finance contact, collaborating with sales, marketing, and operations on pricing, investments, and business cases. \n Cost Management: Monitor and evaluate costs, ensuring budget alignment and identifying cost-saving opportunities without compromising service quality. \n Performance Insights: Track financial KPIs, providing actionable insights to enhance business performance and profitability. \n Process Improvement: Streamline financial processes, implement top practices, and guidance system enhancements for efficiency and accuracy. \n Ad-Hoc Analysis : Provide financial insights to assist business initiatives, projects, and outcomes. Assist senior finance team members with reporting, insight, and financial planning. \n\n What we are looking for from you: \n\n Experience in finance, accounting, business, or a related field. \n 1-2 years of experience in a financial, analytical, or commercial role. \n Experience in financial modeling, Excel, and accounting systems (e.g., SAP, Oracle, or similar). \n Knowledge of commercial operations and drivers of profitability. \n Strong analytical and critical thinking techniques with attention to detail. \n Excellent relationship-building and communication techniques, able to present financial data clearly to non-finance stakeholders. \n Proactive and self-motivated, with a collaborative approach to work. \n\nGet In Touch\n\nFind out how this one-off opportunity can help you to achieve your career goals by making an application to our knowledgeable and friendly Talent Acquisition team. Choose a new path with SHL.\n\n #CareersAtSHL #SHLHiringTalent #HybridRole # salesoperationsjobs #financeanalystjobs #salesjobs\n\nAbout Us\n\nWe unlock the possibilities of businesses through the power of people, science and technology.\nWe started this industry of people insight more than 40 years ago and continue to lead the market with powerhouse product launches, ground-breaking science and business transformation.\nWhen you inspire and transform people’s lives, you will experience the greatest business outcomes possible. SHL’s products insights, experiences, and services can help achieve growth at scale.\n\nWhat SHL Can Offer You\n\nDiversity, equity, inclusion and accessibility are key threads in the fabric of SHL’s business and culture (find out more about DEI and accessibility at SHL )\n\nEmployee benefits package that takes care of you and your family.\nSupport, coaching, and on-the-job development to achieve career success\nA fun and flexible workplace where you’ll be inspired to do your best work (find out more LifeAtSHL )\nThe ability to transform workplaces around the world for others.\n\nSHL is an equal opportunity employer. We support and encourage applications from a diverse range of candidates. We can, and do make adjustments to make sure our recruitment process is as inclusive as possible.',
 'I want to hire Customer support executives who are expert in English communication.  \nWe are looking for talented Customer Support specialists to join our Product operations team in India (Mumbai)\n\n\nMinna connects global banks and fintech with subscription businesses to give consumers self-serve subscription management in-app. Minna is a technology partner to top-tier financial institutions, fintech and subscription businesses, providing subscription management functionality for 50+ million banking and fintech customers across the United States, United Kingdom and Europe.\nMinna builds the infrastructure that links Subscription Merchants (such as Netflix, Spotify, Amazon) to leading Financial Institutions (Lloyds Bank, ING Belgium, Swedbank to name a few). This connection enables consumers to effortlessly manage their subscriptions by performing actions like canceling, pausing, or changing their plans.\n\n\nResponsibilities:\n\nEfficiently manage cancellations and monitor cancellation status for merchants\nInitiate and execute workflows for cancellations at various stages of the cancellation journey with merchants\nProvide friendly and efficient customer service support via chat, calls, emails, and other channels\nFamiliarity with Minna’s Merchant Registry and classifications for merchants, services, and categories\nProficiency in understanding subscription terms and pulling relevant information from internal systems to support Account Management, Sales, and other queries\nConduct outbound calls to customers for subscription management and issue resolution\nHandle incoming queries from customers and merchants, ensuring timely resolution and escalation when necessary\nCollaborate with cross-functional teams to improve processes and enhance the customer experience\nMaintain accurate records and documentation of customer interactions and issue resolutions\n\n\nBased\n\nThis role is based in Mumbai and will require daily commute.\n\n\nRequirements:\n\nFluent in English with a minimum of 2-3 years of work experience in an International Call Center (US Voice Process or UK Voice Process)\nComfortable working full-time in English and willing to work in US or UK shifts, must be flexible with work timings.\nDemonstrated ability to deliver excellent customer service and resolve issues with good judgment\nStrong analytical abilities for troubleshooting and problem-solving\nAppreciation for routine tasks and ability to follow clear instructions\nComfortable multitasking to manage calls, emails, and chats simultaneously in an outbound calling process\nStrong communication skills, both verbal and written, with a friendly and professional tone\nAbility to adapt to a fast-paced and technologically advanced environment\nDetail-oriented with strong organizational skills and the ability to prioritize tasks effectively\n\n\nOur global benefits\n\n25 days holiday plus public holidays\nPrivate health insurance\nSubscription allowance\nFind more information about our benefits here\nMinna is an equal opportunities employer and does not discriminate on the basis of race, nationality, ethnicity, skin colour, religion, disability or sexual orientation. We celebrate and embrace a diverse workforce and are committed to building a team that represents a variety of backgrounds, perspectives and skills.']

In [51]:
len(results)

9

In [71]:
results

[{'query': 'Looking to hire mid-level professionals who are proficient in Python, SQL and Java Script. Need an assessment package that can test all skills with max duration of 60 minutes.',
  'recommendations': [{'title': 'Python (New)',
    'url': 'https://www.shl.com/products/product-catalog/view/python-new/',
    'description': 'Multi-choice test that measures the knowledge of Python programming, databases, modules and library.',
    'job_levels': ['Mid-Professional', 'Professional Individual Contributor'],
    'languages': ['English (USA)'],
    'assessment_length': '11 minutes',
    'test_types': ['Knowledge & Skills'],
    'remote_testing': True,
    'adaptive_irt': False,
    'relevance_reason': 'Directly assesses Python proficiency, a key requirement. It is within the time limit and suitable for mid-level professionals.'},
   {'title': 'JavaScript (New)',
    'url': 'https://www.shl.com/products/product-catalog/view/javascript-new/',
    'description': 'Multi-choice test that measures knowledge of programming in the JavaScript language and its application in front-end development.',
    'job_levels': ['Mid-Professional', 'Professional Individual Contributor'],
    'languages': ['English (USA)'],
    'assessment_length': '9 minutes',
    'test_types': ['Knowledge & Skills'],
    'remote_testing': True,
    'adaptive_irt': False,
    'relevance_reason': 'Directly assesses JavaScript proficiency, a key requirement. It is within the time limit and suitable for mid-level professionals.'},
   {'title': 'SQL (New)',
    'url': 'https://www.shl.com/products/product-catalog/view/sql-new/',
    'description': 'Multi-choice test that measures the knowledge of SQL queries, data manipulation and transaction processing.',
    'job_levels': ['Mid-Professional', 'Professional Individual Contributor'],
    'languages': ['English (USA)'],
    'assessment_length': '9 minutes',
    'test_types': ['Knowledge & Skills'],
    'remote_testing': True,
    'adaptive_irt': False,
    'relevance_reason': 'Directly assesses SQL proficiency, a key requirement. It is within the time limit and suitable for mid-level professionals.'},
   {'title': 'Automata - SQL (New)',
    'url': 'https://www.shl.com/products/product-catalog/view/automata-sql-new/',
    'description': 'A simulated query writing test that measures the ability to write SQL queries to perform DDL, DML and DCL tasks.',
    'job_levels': ['Mid-Professional', 'Professional Individual Contributor'],
    'languages': ['English (USA)'],
    'assessment_length': '30 minutes',
    'test_types': ['Simulations'],
    'remote_testing': True,
    'adaptive_irt': False,
    'relevance_reason': 'Assesses practical SQL skills through simulation, complementing the knowledge-based SQL test. It is within the time limit and suitable for mid-level professionals.'},
   {'title': 'Programming Concepts',
    'url': 'https://www.shl.com/products/product-catalog/view/programming-concepts/',
    'description': 'The Programming Concepts test measures knowledge of the core aspects of computer science programming that is valid across programming languages. Designed for all programmers, this test covers the following topics:  Algorithms, Complex Data Types, Data Access, Productivity and Quality, Program Flow, Program Structure, Programming Paradigms, User Interface, Variables, Data Types, and Operators.',
    'job_levels': ['Mid-Professional', 'Professional Individual Contributor'],
    'languages': ['English (USA)'],
    'assessment_length': '25 minutes',
    'test_types': ['Knowledge & Skills'],
    'remote_testing': True,
    'adaptive_irt': True,
    'relevance_reason': 'Provides a foundational understanding of programming principles relevant to all the required languages. It is within the time limit and suitable for mid-level professionals.'},
   {'title': 'Automata Front End',
    'url': 'https://www.shl.com/products/product-catalog/view/automata-front-end/',
    'description': 'Simulation based test that measures the front-end development capabilities using HTML, CSS, and JavaScript. The candidate is provided with 3 different sections to code in HTML, CSS and JavaScript respectively and a separate output section to view the output. This simulation is then manually scored.',
    'job_levels': ['Entry-Level',
     'Graduate',
     'Mid-Professional',
     'Professional Individual Contributor',
     'Manager'],
    'languages': ['English (USA)'],
    'assessment_length': '30 minutes',
    'test_types': ['Simulations'],
    'remote_testing': True,
    'adaptive_irt': False,
    'relevance_reason': 'Assesses practical JavaScript skills in a simulated environment, which is highly relevant for front-end development roles. It is within the time limit and suitable for mid-level professionals.'},
   {'title': 'SQL Server Integration Services (SSIS) (New)',
    'url': 'https://www.shl.com/products/product-catalog/view/sql-server-integration-services-ssis-new/',
    'description': 'Multi-choice test that measures the knowledge of SSIS architecture, components, control flow, data flow, transformation, SQL server tasks, SSIS administration, debugging, logging, security deployment, performance, package scheduling, execution and configuration.',
    'job_levels': ['Mid-Professional', 'Professional Individual Contributor'],
    'languages': ['English (USA)'],
    'assessment_length': '10 minutes',
    'test_types': ['Knowledge & Skills'],
    'remote_testing': True,
    'adaptive_irt': False,
    'relevance_reason': 'While specific to SSIS, it tests SQL Server knowledge which is often related to SQL proficiency. It is within the time limit and suitable for mid-level professionals.'}],
  'reasoning': 'The recommended assessments cover the core requirements of Python, SQL, and JavaScript proficiency for mid-level professionals. The selection includes both knowledge-based tests and simulations to assess practical application of skills. All recommended assessments are within the specified 60-minute individual time limit and are suitable for the target job level. The combination provides a comprehensive evaluation of the required technical skills.'},
 {'query': 'Looking to hire mid-level professionals who are proficient in Python, SQL and Java Script. Need an assessment package that can test all skills with max duration of 60 minutes.',
  'recommendations': [{'title': 'Python (New)',
    'url': 'https://www.shl.com/products/product-catalog/view/python-new/',
    'description': 'Multi-choice test that measures the knowledge of Python programming, databases, modules and library.',
    'job_levels': ['Mid-Professional', 'Professional Individual Contributor'],
    'languages': ['English (USA)'],
    'assessment_length': '11 minutes',
    'test_types': ['Knowledge & Skills'],
    'remote_testing': True,
    'adaptive_irt': False,
    'relevance_reason': 'Directly assesses Python proficiency, a key requirement. It is within the time limit and suitable for mid-level professionals.'},
   {'title': 'JavaScript (New)',
    'url': 'https://www.shl.com/products/product-catalog/view/javascript-new/',
    'description': 'Multi-choice test that measures knowledge of programming in the JavaScript language and its application in front-end development.',
    'job_levels': ['Mid-Professional', 'Professional Individual Contributor'],
    'languages': ['English (USA)'],
    'assessment_length': '9 minutes',
    'test_types': ['Knowledge & Skills'],
    'remote_testing': True,
    'adaptive_irt': False,
    'relevance_reason': 'Directly assesses JavaScript proficiency, a key requirement. It is within the time limit and suitable for mid-level professionals.'},
   {'title': 'SQL (New)',
    'url': 'https://www.shl.com/products/product-catalog/view/sql-new/',
    'description': 'Multi-choice test that measures the knowledge of SQL queries, data manipulation and transaction processing.',
    'job_levels': ['Mid-Professional', 'Professional Individual Contributor'],
    'languages': ['English (USA)'],
    'assessment_length': '9 minutes',
    'test_types': ['Knowledge & Skills'],
    'remote_testing': True,
    'adaptive_irt': False,
    'relevance_reason': 'Directly assesses SQL proficiency, a key requirement. It is within the time limit and suitable for mid-level professionals.'},
   {'title': 'Automata - SQL (New)',
    'url': 'https://www.shl.com/products/product-catalog/view/automata-sql-new/',
    'description': 'A simulated query writing test that measures the ability to write SQL queries to perform DDL, DML and DCL tasks.',
    'job_levels': ['Mid-Professional', 'Professional Individual Contributor'],
    'languages': ['English (USA)'],
    'assessment_length': '30 minutes',
    'test_types': ['Simulations'],
    'remote_testing': True,
    'adaptive_irt': False,
    'relevance_reason': 'Assesses practical SQL skills through simulation, complementing the knowledge-based SQL test. It is within the time limit and suitable for mid-level professionals.'},
   {'title': 'Programming Concepts',
    'url': 'https://www.shl.com/products/product-catalog/view/programming-concepts/',
    'description': 'The Programming Concepts test measures knowledge of the core aspects of computer science programming that is valid across programming languages. Designed for all programmers, this test covers the following topics:  Algorithms, Complex Data Types, Data Access, Productivity and Quality, Program Flow, Program Structure, Programming Paradigms, User Interface, Variables, Data Types, and Operators.',
    'job_levels': ['Mid-Professional', 'Professional Individual Contributor'],
    'languages': ['English (USA)'],
    'assessment_length': '25 minutes',
    'test_types': ['Knowledge & Skills'],
    'remote_testing': True,
    'adaptive_irt': True,
    'relevance_reason': 'Provides a foundational understanding of programming principles relevant to all the required languages. It is within the time limit and suitable for mid-level professionals.'},
   {'title': 'Automata Front End',
    'url': 'https://www.shl.com/products/product-catalog/view/automata-front-end/',
    'description': 'Simulation based test that measures the front-end development capabilities using HTML, CSS, and JavaScript. The candidate is provided with 3 different sections to code in HTML, CSS and JavaScript respectively and a separate output section to view the output. This simulation is then manually scored.',
    'job_levels': ['Entry-Level',
     'Graduate',
     'Mid-Professional',
     'Professional Individual Contributor',
     'Manager'],
    'languages': ['English (USA)'],
    'assessment_length': '30 minutes',
    'test_types': ['Simulations'],
    'remote_testing': True,
    'adaptive_irt': False,
    'relevance_reason': 'Assesses practical JavaScript skills in a simulated environment, which is highly relevant for front-end development roles. It is within the time limit and suitable for mid-level professionals.'},
   {'title': 'SQL Server Integration Services (SSIS) (New)',
    'url': 'https://www.shl.com/products/product-catalog/view/sql-server-integration-services-ssis-new/',
    'description': 'Multi-choice test that measures the knowledge of SSIS architecture, components, control flow, data flow, transformation, SQL server tasks, SSIS administration, debugging, logging, security deployment, performance, package scheduling, execution and configuration.',
    'job_levels': ['Mid-Professional', 'Professional Individual Contributor'],
    'languages': ['English (USA)'],
    'assessment_length': '10 minutes',
    'test_types': ['Knowledge & Skills'],
    'remote_testing': True,
    'adaptive_irt': False,
    'relevance_reason': 'While specific to SSIS, it tests SQL Server knowledge which is often related to SQL proficiency. It is within the time limit and suitable for mid-level professionals.'}],
  'reasoning': 'The recommended assessments cover the core requirements of Python, SQL, and JavaScript proficiency for mid-level professionals. The selection includes both knowledge-based tests and simulations to assess practical application of skills. All recommended assessments are within the specified 60-minute individual time limit and are suitable for the target job level. The combination provides a comprehensive evaluation of the required technical skills.'},
 {'query': 'Job Description\n\n Join a community that is shaping the future of work! \n\n SHL, People Science. People Answers. \n\nAre you an AI enthusiastwith visionary thinking to conceptualize AI-based products? Are you looking to apply these skills in an environment where teamwork and collaboration are key to developing our digital product experiences? We are seeking a Research Engineer to join our team to deliver robust AI/ML models. You will closely work with the product team to spot opportunities to use AI in the current product stack and influence the product roadmap by incorporating AI-led features/products.\n\nAn excellent benefits package is offered in a culture where career development, with ongoing manager guidance, collaboration, flexibility, diversity, and inclusivity are all intrinsic to our culture.\u202f There is a huge investment in SHL currently so there’s no better time to become a part of something transformational.\n\nWhat You Will Be Doing\n\n Develop and experiment with machine learning models like NLP, computer vision etc. \n Prototype and fine-tune generative AI models for text, image, speech, and video generation. \n Implement emerging LLM technologies and monitoring tools. \n Manage the entire AI/ML lifecycle from research to deployment and maintenance. \n Optimize models for scalability, efficiency, and performance. \n Collaborate with ML engineers for solution delivery and propose AI-driven enhancements. \n Contribute to research, documentation, and publications with AI/ML advancements. \n\nEssential\n\nWhat we are looking for from you:\n\n Relevant experience in AI/ML - NLP, speech processing, and computer vision. \n Proficiency in Python and ML frameworks such as TensorFlow, PyTorch, & OpenAI APIs. \n Good knowledge of ML theory deep learning, and statistical modeling. \n\nDesirable\n\n Familiarity with Generative AI (LLMs & RAG). \n Experience in prototyping and deploying AI. \n Agile and proactive thinking. \n\nGet In Touch\n\nFind out how this one-off opportunity can help you to achieve your career goals by making an application to our knowledgeable and friendly Talent Acquisition team. Choose a new path with SHL.\n\n #CareersAtSHL #SHLHiringTalent \n\n#AIJobs #ResearchJobs #MLJobs\n\n#CareerOpportunities #JobOpportunities \n\nAbout Us\n\n We unlock the possibilities of businesses through the power of people, science and technology. \n We started this industry of people insight more than 40 years ago and continue to lead the market with powerhouse product launches, ground-breaking science and business transformation. \n When you inspire and transform people’s lives, you will experience the greatest business outcomes possible. SHL’s products insights, experiences, and services can help achieve growth at scale. \n\nWhat SHL Can Offer You\n\n Diversity, equity, inclusion and accessibility are key threads in the fabric of SHL’s business and culture (find out more about DEI and accessibility at SHL ) \n Employee benefits package that takes care of you and your family. \n Support, coaching, and on-the-job development to achieve career success \n A fun and flexible workplace where you’ll be inspired to do your best work (find out more LifeAtSHL ) \n The ability to transform workplaces around the world for others. \n\nSHL is an equal opportunity employer. We support and encourage applications from a diverse range of candidates. We can, and do make adjustments to make sure our recruitment process is as inclusive as possible.\n\nCan you recommend some assessment that can help me screen applications. Time limit is less than 30 minutes',
  'recommendations': [{'title': 'AI Skills',
    'url': 'https://www.shl.com/products/product-catalog/view/ai-skills/',
    'description': 'The AI Skills assessment measures the skills that help candidates successfully leverage AI in their work.',
    'job_levels': ['General Population'],
    'languages': ['English (USA)'],
    'assessment_length': '16 minutes',
    'test_types': ['Personality & Behavior'],
    'remote_testing': True,
    'adaptive_irt': False,
    'relevance_reason': 'Directly assesses skills related to leveraging AI, which is central to the Research Engineer role. It fits within the time limit and measures relevant behavioral tendencies.'},
   {'title': 'Data Science (New)',
    'url': 'https://www.shl.com/products/product-catalog/view/data-science-new/',
    'description': 'Multi-choice test that measures the conceptual knowledge on how to use machine learning to analyze data, extract information, draw conclusions and make statistically-driven decisions.',
    'job_levels': ['Mid-Professional', 'Professional Individual Contributor'],
    'languages': ['English (USA)'],
    'assessment_length': '14 minutes',
    'test_types': ['Knowledge & Skills'],
    'remote_testing': True,
    'adaptive_irt': False,
    'relevance_reason': 'Measures foundational knowledge in data science and machine learning, which are essential for developing AI/ML models. It is well within the time limit.'},
   {'title': 'Programming Concepts',
    'url': 'https://www.shl.com/products/product-catalog/view/programming-concepts/',
    'description': 'The Programming Concepts test measures knowledge of the core aspects of computer science programming that is valid across programming languages. Designed for all programmers, this test covers the following topics: Algorithms, Complex Data Types, Data Access, Productivity and Quality, Program Flow, Program Structure, Programming Paradigms, User Interface, Variables, Data Types, and Operators.',
    'job_levels': ['Mid-Professional', 'Professional Individual Contributor'],
    'languages': ['English (USA)'],
    'assessment_length': '25 minutes',
    'test_types': ['Knowledge & Skills'],
    'remote_testing': True,
    'adaptive_irt': True,
    'relevance_reason': 'Assesses fundamental programming knowledge crucial for implementing AI/ML models and working with frameworks like TensorFlow and PyTorch. It fits within the time limit.'},
   {'title': 'Agile Software Development',
    'url': 'https://www.shl.com/products/product-catalog/view/agile-software-development/',
    'description': 'Multi-choice test that measures the knowledge of agile methodology, scrum, feature driven software development, incremental and iterative development and processes involved in agile software development.',
    'job_levels': ['Graduate'],
    'languages': ['English (USA)'],
    'assessment_length': '7 minutes',
    'test_types': ['Knowledge & Skills'],
    'remote_testing': True,
    'adaptive_irt': False,
    'relevance_reason': 'The role involves collaboration with product teams and potentially working in an agile environment. This assessment checks for knowledge of agile methodologies and is very short.'},
   {'title': 'Dojo (New)',
    'url': 'https://www.shl.com/products/product-catalog/view/dojo-new/',
    'description': 'Multi-choice test that measures the knowledge of Dojo architecture, classes and libraries, styles, animation and Dojo queries.',
    'job_levels': ['Mid-Professional', 'Professional Individual Contributor'],
    'languages': ['English (USA)'],
    'assessment_length': '11 minutes',
    'test_types': ['Knowledge & Skills'],
    'remote_testing': True,
    'adaptive_irt': False,
    'relevance_reason': "While specific to Dojo, it's a knowledge-based assessment within the time limit that could indicate a candidate's breadth of technical knowledge in web development frameworks, which can be relevant for prototyping and deployment."},
   {'title': 'Conversational Multichat Simulation',

In [59]:
for i,result in enumerate(results):
    print(i,result['query'])

0 Looking to hire mid-level professionals who are proficient in Python, SQL and Java Script. Need an assessment package that can test all skills with max duration of 60 minutes.
1 Looking to hire mid-level professionals who are proficient in Python, SQL and Java Script. Need an assessment package that can test all skills with max duration of 60 minutes.
2 Job Description

 Join a community that is shaping the future of work!

 SHL, People Science. People Answers.

Are you an AI enthusiastwith visionary thinking to conceptualize AI-based products? Are you looking to apply these skills in an environment where teamwork and collaboration are key to developing our digital product experiences? We are seeking a Research Engineer to join our team to deliver robust AI/ML models. You will closely work with the product team to spot opportunities to use AI in the current product stack and influence the product roadmap by incorporating AI-led features/products.

An excellent benefits package is offered in a culture where career development, with ongoing manager guidance, collaboration, flexibility, diversity, and inclusivity are all intrinsic to our culture.  There is a huge investment in SHL currently so there’s no better time to become a part of something transformational.

What You Will Be Doing

 Develop and experiment with machine learning models like NLP, computer vision etc.
 Prototype and fine-tune generative AI models for text, image, speech, and video generation.
 Implement emerging LLM technologies and monitoring tools.
 Manage the entire AI/ML lifecycle from research to deployment and maintenance.
 Optimize models for scalability, efficiency, and performance.
 Collaborate with ML engineers for solution delivery and propose AI-driven enhancements.
 Contribute to research, documentation, and publications with AI/ML advancements.

Essential

What we are looking for from you:

 Relevant experience in AI/ML - NLP, speech processing, and computer vision.
 Proficiency in Python and ML frameworks such as TensorFlow, PyTorch, & OpenAI APIs.
 Good knowledge of ML theory deep learning, and statistical modeling.

Desirable

 Familiarity with Generative AI (LLMs & RAG).
 Experience in prototyping and deploying AI.
 Agile and proactive thinking.

Get In Touch

Find out how this one-off opportunity can help you to achieve your career goals by making an application to our knowledgeable and friendly Talent Acquisition team. Choose a new path with SHL.

 #CareersAtSHL #SHLHiringTalent

#AIJobs #ResearchJobs #MLJobs

#CareerOpportunities #JobOpportunities

About Us

 We unlock the possibilities of businesses through the power of people, science and technology.
 We started this industry of people insight more than 40 years ago and continue to lead the market with powerhouse product launches, ground-breaking science and business transformation.
 When you inspire and transform people’s lives, you will experience the greatest business outcomes possible. SHL’s products insights, experiences, and services can help achieve growth at scale.

What SHL Can Offer You

 Diversity, equity, inclusion and accessibility are key threads in the fabric of SHL’s business and culture (find out more about DEI and accessibility at SHL )
 Employee benefits package that takes care of you and your family.
 Support, coaching, and on-the-job development to achieve career success
 A fun and flexible workplace where you’ll be inspired to do your best work (find out more LifeAtSHL )
 The ability to transform workplaces around the world for others.

SHL is an equal opportunity employer. We support and encourage applications from a diverse range of candidates. We can, and do make adjustments to make sure our recruitment process is as inclusive as possible.

Can you recommend some assessment that can help me screen applications. Time limit is less than 30 minutes
3 I am hiring for an analyst and wants applications to screen using Cognitive and personality tests, what options are available within 45 mins.
4 I have a JD Job Description

 People Science. People Answers  !

Do you love contributing to commercial growth and success? Join as a Presales Specialist! In this role, you’ll support the Presales function and commercial teams by building custom client demos, developing RFP responses, writing high quality Statements of Work, ensuring our deals are appropriately scoped and priced.

An excellent benefits package is offered in a culture where career development, with ongoing manager guidance, collaboration, flexibility, diversity and inclusivity are all intrinsic to our culture. There is a huge investment in SHL currently so there ’ s no better time to become a part of something transformational. Hybrid working is available

This role is based in the US. Candidates must be eligible to work in the US without sponsorship. SHL does not offer visa sponsorship.

The Presales Specialist is responsible for creating, curating, and presenting compelling content to support the Solution Architects and Sales team during the presales phase. This includes:

 Building custom demos
 Responding to RFPs
 Maintaining knowledge of SHL commercial offerings, pricing, and platforms.
 Scoping support for commercial opportunities
 Creating compelling proposals
 Presenting Solution Vision to Customers
 Ensuring successful handover from pre-sales to delivery teams
 Maintaining domain expertise in the Talent Intelligence and HCM space

Key Responsibilities

 Content Creation and Customization:

 Develop customized content, including proposal (RFI/RFP) presentations, product demos and Word/Excel proposals, to support the presales process.
 Create engaging content that clearly communicates the value proposition of SHL’s solutions and services
 Collaborate with Solution Architects and sales teams to ensure content aligns with client requirements, business goals, strategy

 Collaboration with Sales and Technical (CoE) Teams:

 Work closely with Centre of Excellence to understand client technical requirements and submission planning.
 Professional Services: be an expert on what products and services we deliver. Ensure all aspects of client engagements can be delivered and set realistic timelines
 Product: Allowing a solid understanding of our solutions and stay appraised of digital roadmap and releases

Customer Engagement

 Support sales teams getting ready for client meetings, demos, and presentations
 Help refine product positioning and messaging to resonate with the client’s industry and business context.

Content Strategy And Development

 Develop and maintain a local library of reusable content, templates, and resources for presales presentations, proposals, and client demos.
 Continuously assess the effectiveness of content and iterate based on client feedback and sales outcomes.
 Stay up to date with industry trends, competitor content, and customer preferences to enhance content quality

 Required Skills and Qualifications:

 Qualification in Technology, Marketing, Communications, Business, or a related field
 Ideally 2-4 years of experience in a Presales or commercial operations preferably within a technology, SaaS or services industry.
 Strong writing, editing, and presentation skills with an ability to craft clear, persuasive, and engaging content.
 Experience with design tools (e.g., PowerPoint, Synthesia, Adobe, Canva).
 Strong communication and collaboration skills to work cross-functional teams.
 Ability to quickly understand customer needs and develop content that resonates with different audiences.
 Attention to detail and ability to manage multiple content development projects simultaneously.
 Utility player! You thrive in the unknown and enjoy wearing multiple hats

Desirable

 Presales tools: Walnut, Custom Report Developer tools
 Marketing skills: Canva, Synthesia
 Contracting skills: Experience writing Statements of work
 Proposal skills: populating responses to RFPs, Loopio
 Technical skills: understanding of HR technology and workflows. Experience solutioning complex integrations.

Get In Touch

Find out how this one-off opportunity can help you to achieve your career goals by making an application to our knowledgeable Talent Acquisition team. Choose a new path with SHL.

#PreSalesOperations #SHL #CareersAtSHL

About Us

We unlock the possibilities of businesses through the power of people, science and technology.
We started this industry of people insight more than 40 years ago and continue to lead the market with powerhouse product launches, ground-breaking science and business transformation.
When you inspire and transform people’s lives, you will experience the greatest business outcomes possible. SHL’s products insights, experiences, and services can help achieve growth at scale.

What SHL Can Offer You

Diversity, equity, inclusion and accessibility are key threads in the fabric of SHL’s business and culture (find out more about DEI and accessibility at SHL )

Employee benefits package that takes care of you and your family.
Support, coaching, and on-the-job development to achieve career success
A fun and flexible workplace where you’ll be inspired to do your best work (find out more LifeAtSHL )
The ability to transform workplaces around the world for others.

SHL is an equal opportunity employer. We support and encourage applications from a diverse range of candidates. We can, and do make adjustments to make sure our recruitment process is as inclusive as possible.

Here and I have want them to give a test which is atleast  30 mins long
5 I am new looking for new graduates in my sales team, suggest an 30 min long assessment
6 For Marketing - Content Writer Position

Department: Marketing

Location: Gurugram

About Company

ShopClues.com is India's leading e-commerce platform that is focused on changing the shopping scenario of the country. We are the one-stop platform for everything from electronics to fashion to home & kitchen. The company visions to be the largest and most customer-centric e-commerce platform for India.

ShopClues.com has been operating out of Silicon Valley since February 2011 and has its headquarters in Gurugram. The Company launched its Beta version on 26th January 2012 and has been constantly evolving since then for the better.

Our Culture

We are a team of enthusiastic and determined individuals, who believe in working together with lots of energy, bringing continuous innovations to the organization, and celebrating every bit of it. We provide equal opportunity to each individual and look forward to executing the best ideas.

The Typical Creative Process Involves

Discussing the campaign's core message and target audience
Brainstorming visual and copy ideas with other members of the creative team
Visualizing different forms of communication approaches for various marketing platforms like Website, Email, Social, etc. for ShopClues.
Generating Stories for Brands core blog, and other content-driven platforms.
Overseeing the production phase till the final output.
Experience in the publishing of Push Notification and unique Product Description.
7 Suggest me an assessment for the JD below Job Description

 Find purpose in each day while contributing to a workplace revolution! SHL, People Science. People Answers.

Are you a driven business professional eager to develop your career by contributing directly to business success? SHL is seeking a Finance & Operations Analyst to join our AMS team!

 The Finance & Operations Analyst  will provide insights, analysis, and guidance to commercial teams to drive informed outcomes. This role bridges the gap between finance & operations and the business, ensuring alignment with the organization’s strategic goals and delivering value-added advice to improve performance.

An excellent benefits package is offered in a culture where career development, with ongoing manager guidance, collaboration, flexibility, diversity and inclusivity are all intrinsic to our culture.  There is a huge investment in SHL currently so there’s no better time to become a part of something transformational.  Hybrid working is available.

What You Will Be Doing

 Financial Reporting: Deliver accurate monthly management accounts, variance evaluation, and KPI insights to help data-driven decision-making.
 Budgeting & Forecasting: Assist in preparing budgets and forecasts, identifying financial risks, opportunities, and recommending strategic actions.
 Business Partnering: Act as the primary finance contact, collaborating with sales, marketing, and operations on pricing, investments, and business cases.
 Cost Management: Monitor and evaluate costs, ensuring budget alignment and identifying cost-saving opportunities without compromising service quality.
 Performance Insights: Track financial KPIs, providing actionable insights to enhance business performance and profitability.
 Process Improvement: Streamline financial processes, implement top practices, and guidance system enhancements for efficiency and accuracy.
 Ad-Hoc Analysis : Provide financial insights to assist business initiatives, projects, and outcomes. Assist senior finance team members with reporting, insight, and financial planning.

 What we are looking for from you:

 Experience in finance, accounting, business, or a related field.
 1-2 years of experience in a financial, analytical, or commercial role.
 Experience in financial modeling, Excel, and accounting systems (e.g., SAP, Oracle, or similar).
 Knowledge of commercial operations and drivers of profitability.
 Strong analytical and critical thinking techniques with attention to detail.
 Excellent relationship-building and communication techniques, able to present financial data clearly to non-finance stakeholders.
 Proactive and self-motivated, with a collaborative approach to work.

Get In Touch

Find out how this one-off opportunity can help you to achieve your career goals by making an application to our knowledgeable and friendly Talent Acquisition team. Choose a new path with SHL.

 #CareersAtSHL #SHLHiringTalent #HybridRole # salesoperationsjobs #financeanalystjobs #salesjobs

About Us

We unlock the possibilities of businesses through the power of people, science and technology.
We started this industry of people insight more than 40 years ago and continue to lead the market with powerhouse product launches, ground-breaking science and business transformation.
When you inspire and transform people’s lives, you will experience the greatest business outcomes possible. SHL’s products insights, experiences, and services can help achieve growth at scale.

What SHL Can Offer You

Diversity, equity, inclusion and accessibility are key threads in the fabric of SHL’s business and culture (find out more about DEI and accessibility at SHL )

Employee benefits package that takes care of you and your family.
Support, coaching, and on-the-job development to achieve career success
A fun and flexible workplace where you’ll be inspired to do your best work (find out more LifeAtSHL )
The ability to transform workplaces around the world for others.

SHL is an equal opportunity employer. We support and encourage applications from a diverse range of candidates. We can, and do make adjustments to make sure our recruitment process is as inclusive as possible.
8 I want to hire Customer support executives who are expert in English communication.
We are looking for talented Customer Support specialists to join our Product operations team in India (Mumbai)


Minna connects global banks and fintech with subscription businesses to give consumers self-serve subscription management in-app. Minna is a technology partner to top-tier financial institutions, fintech and subscription businesses, providing subscription management functionality for 50+ million banking and fintech customers across the United States, United Kingdom and Europe.
Minna builds the infrastructure that links Subscription Merchants (such as Netflix, Spotify, Amazon) to leading Financial Institutions (Lloyds Bank, ING Belgium, Swedbank to name a few). This connection enables consumers to effortlessly manage their subscriptions by performing actions like canceling, pausing, or changing their plans.


Responsibilities:

Efficiently manage cancellations and monitor cancellation status for merchants
Initiate and execute workflows for cancellations at various stages of the cancellation journey with merchants
Provide friendly and efficient customer service support via chat, calls, emails, and other channels
Familiarity with Minna’s Merchant Registry and classifications for merchants, services, and categories
Proficiency in understanding subscription terms and pulling relevant information from internal systems to support Account Management, Sales, and other queries
Conduct outbound calls to customers for subscription management and issue resolution
Handle incoming queries from customers and merchants, ensuring timely resolution and escalation when necessary
Collaborate with cross-functional teams to improve processes and enhance the customer experience
Maintain accurate records and documentation of customer interactions and issue resolutions


Based

This role is based in Mumbai and will require daily commute.


Requirements:

Fluent in English with a minimum of 2-3 years of work experience in an International Call Center (US Voice Process or UK Voice Process)
Comfortable working full-time in English and willing to work in US or UK shifts, must be flexible with work timings.
Demonstrated ability to deliver excellent customer service and resolve issues with good judgment
Strong analytical abilities for troubleshooting and problem-solving
Appreciation for routine tasks and ability to follow clear instructions
Comfortable multitasking to manage calls, emails, and chats simultaneously in an outbound calling process
Strong communication skills, both verbal and written, with a friendly and professional tone
Ability to adapt to a fast-paced and technologically advanced environment
Detail-oriented with strong organizational skills and the ability to prioritize tasks effectively


Our global benefits

25 days holiday plus public holidays
Private health insurance
Subscription allowance
Find more information about our benefits here
Minna is an equal opportunities employer and does not discriminate on the basis of race, nationality, ethnicity, skin colour, religion, disability or sexual orientation. We celebrate and embrace a diverse workforce and are committed to building a team that represents a variety of backgrounds, perspectives and skills.

In [63]:
results[4]['query']

'I have a JD Job Description\n\n People Science. People Answers  !\n\nDo you love contributing to commercial growth and success? Join as a Presales Specialist! In this role, you’ll support the Presales function and commercial teams by building custom client demos, developing RFP responses, writing high quality Statements of Work, ensuring our deals are appropriately scoped and priced.\n\nAn excellent benefits package is offered in a culture where career development, with ongoing manager guidance, collaboration, flexibility, diversity and inclusivity are all intrinsic to our culture. There is a huge investment in SHL currently so there ’ s no better time to become a part of something transformational. Hybrid working is available\n\nThis role is based in the US. Candidates must be eligible to work in the US without sponsorship. SHL does not offer visa sponsorship.\n\nThe Presales Specialist is responsible for creating, curating, and presenting compelling content to support the Solution Architects and Sales team during the presales phase. This includes:\n\n Building custom demos \n Responding to RFPs \n Maintaining knowledge of SHL commercial offerings, pricing, and platforms. \n Scoping support for commercial opportunities \n Creating compelling proposals \n Presenting Solution Vision to Customers \n Ensuring successful handover from pre-sales to delivery teams \n Maintaining domain expertise in the Talent Intelligence and HCM space \n\nKey Responsibilities\n\n Content Creation and Customization: \n\n Develop customized content, including proposal (RFI/RFP) presentations, product demos and Word/Excel proposals, to support the presales process. \n Create engaging content that clearly communicates the value proposition of SHL’s solutions and services \n Collaborate with Solution Architects and sales teams to ensure content aligns with client requirements, business goals, strategy \n\n Collaboration with Sales and Technical (CoE) Teams: \n\n Work closely with Centre of Excellence to understand client technical requirements and submission planning. \n Professional Services: be an expert on what products and services we deliver. Ensure all aspects of client engagements can be delivered and set realistic timelines \n Product: Allowing a solid understanding of our solutions and stay appraised of digital roadmap and releases \n\nCustomer Engagement\n\n Support sales teams getting ready for client meetings, demos, and presentations \n Help refine product positioning and messaging to resonate with the client’s industry and business context. \n\nContent Strategy And Development\n\n Develop and maintain a local library of reusable content, templates, and resources for presales presentations, proposals, and client demos. \n Continuously assess the effectiveness of content and iterate based on client feedback and sales outcomes. \n Stay up to date with industry trends, competitor content, and customer preferences to enhance content quality \n\n Required Skills and Qualifications: \n\n Qualification in Technology, Marketing, Communications, Business, or a related field \n Ideally 2-4 years of experience in a Presales or commercial operations preferably within a technology, SaaS or services industry. \n Strong writing, editing, and presentation skills with an ability to craft clear, persuasive, and engaging content. \n Experience with design tools (e.g., PowerPoint, Synthesia, Adobe, Canva). \n Strong communication and collaboration skills to work cross-functional teams. \n Ability to quickly understand customer needs and develop content that resonates with different audiences. \n Attention to detail and ability to manage multiple content development projects simultaneously. \n Utility player! You thrive in the unknown and enjoy wearing multiple hats \n\nDesirable\n\n Presales tools: Walnut, Custom Report Developer tools \n Marketing skills: Canva, Synthesia \n Contracting skills: Experience writing Statements of work \n Proposal skills: populating responses to RFPs, Loopio \n Technical skills: understanding of HR technology and workflows. Experience solutioning complex integrations. \n\nGet In Touch\n\nFind out how this one-off opportunity can help you to achieve your career goals by making an application to our knowledgeable Talent Acquisition team. Choose a new path with SHL. \n\n#PreSalesOperations #SHL #CareersAtSHL \n\nAbout Us\n\nWe unlock the possibilities of businesses through the power of people, science and technology.\nWe started this industry of people insight more than 40 years ago and continue to lead the market with powerhouse product launches, ground-breaking science and business transformation.\nWhen you inspire and transform people’s lives, you will experience the greatest business outcomes possible. SHL’s products insights, experiences, and services can help achieve growth at scale.\n\nWhat SHL Can Offer You\n\nDiversity, equity, inclusion and accessibility are key threads in the fabric of SHL’s business and culture (find out more about DEI and accessibility at SHL )\n\nEmployee benefits package that takes care of you and your family.\nSupport, coaching, and on-the-job development to achieve career success\nA fun and flexible workplace where you’ll be inspired to do your best work (find out more LifeAtSHL )\nThe ability to transform workplaces around the world for others.\n\nSHL is an equal opportunity employer. We support and encourage applications from a diverse range of candidates. We can, and do make adjustments to make sure our recruitment process is as inclusive as possible.\n\nHere and I have want them to give a test which is atleast  30 mins long'

In [57]:
queries

['Looking to hire mid-level professionals who are proficient in Python, SQL and Java Script. Need an assessment package that can test all skills with max duration of 60 minutes.',
 'Job Description\n\n Join a community that is shaping the future of work! \n\n SHL, People Science. People Answers. \n\nAre you an AI enthusiastwith visionary thinking to conceptualize AI-based products? Are you looking to apply these skills in an environment where teamwork and collaboration are key to developing our digital product experiences? We are seeking a Research Engineer to join our team to deliver robust AI/ML models. You will closely work with the product team to spot opportunities to use AI in the current product stack and influence the product roadmap by incorporating AI-led features/products.\n\nAn excellent benefits package is offered in a culture where career development, with ongoing manager guidance, collaboration, flexibility, diversity, and inclusivity are all intrinsic to our culture.\u202f There is a huge investment in SHL currently so there’s no better time to become a part of something transformational.\n\nWhat You Will Be Doing\n\n Develop and experiment with machine learning models like NLP, computer vision etc. \n Prototype and fine-tune generative AI models for text, image, speech, and video generation. \n Implement emerging LLM technologies and monitoring tools. \n Manage the entire AI/ML lifecycle from research to deployment and maintenance. \n Optimize models for scalability, efficiency, and performance. \n Collaborate with ML engineers for solution delivery and propose AI-driven enhancements. \n Contribute to research, documentation, and publications with AI/ML advancements. \n\nEssential\n\nWhat we are looking for from you:\n\n Relevant experience in AI/ML - NLP, speech processing, and computer vision. \n Proficiency in Python and ML frameworks such as TensorFlow, PyTorch, & OpenAI APIs. \n Good knowledge of ML theory deep learning, and statistical modeling. \n\nDesirable\n\n Familiarity with Generative AI (LLMs & RAG). \n Experience in prototyping and deploying AI. \n Agile and proactive thinking. \n\nGet In Touch\n\nFind out how this one-off opportunity can help you to achieve your career goals by making an application to our knowledgeable and friendly Talent Acquisition team. Choose a new path with SHL.\n\n #CareersAtSHL #SHLHiringTalent \n\n#AIJobs #ResearchJobs #MLJobs\n\n#CareerOpportunities #JobOpportunities \n\nAbout Us\n\n We unlock the possibilities of businesses through the power of people, science and technology. \n We started this industry of people insight more than 40 years ago and continue to lead the market with powerhouse product launches, ground-breaking science and business transformation. \n When you inspire and transform people’s lives, you will experience the greatest business outcomes possible. SHL’s products insights, experiences, and services can help achieve growth at scale. \n\nWhat SHL Can Offer You\n\n Diversity, equity, inclusion and accessibility are key threads in the fabric of SHL’s business and culture (find out more about DEI and accessibility at SHL ) \n Employee benefits package that takes care of you and your family. \n Support, coaching, and on-the-job development to achieve career success \n A fun and flexible workplace where you’ll be inspired to do your best work (find out more LifeAtSHL ) \n The ability to transform workplaces around the world for others. \n\nSHL is an equal opportunity employer. We support and encourage applications from a diverse range of candidates. We can, and do make adjustments to make sure our recruitment process is as inclusive as possible.\n\nCan you recommend some assessment that can help me screen applications. Time limit is less than 30 minutes',
 'I am hiring for an analyst and wants applications to screen using Cognitive and personality tests, what options are available within 45 mins.',
 'I have a JD Job Description\n\n People Science. People Answers  !\n\nDo you love contributing to commercial growth and success? Join as a Presales Specialist! In this role, you’ll support the Presales function and commercial teams by building custom client demos, developing RFP responses, writing high quality Statements of Work, ensuring our deals are appropriately scoped and priced.\n\nAn excellent benefits package is offered in a culture where career development, with ongoing manager guidance, collaboration, flexibility, diversity and inclusivity are all intrinsic to our culture. There is a huge investment in SHL currently so there ’ s no better time to become a part of something transformational. Hybrid working is available\n\nThis role is based in the US. Candidates must be eligible to work in the US without sponsorship. SHL does not offer visa sponsorship.\n\nThe Presales Specialist is responsible for creating, curating, and presenting compelling content to support the Solution Architects and Sales team during the presales phase. This includes:\n\n Building custom demos \n Responding to RFPs \n Maintaining knowledge of SHL commercial offerings, pricing, and platforms. \n Scoping support for commercial opportunities \n Creating compelling proposals \n Presenting Solution Vision to Customers \n Ensuring successful handover from pre-sales to delivery teams \n Maintaining domain expertise in the Talent Intelligence and HCM space \n\nKey Responsibilities\n\n Content Creation and Customization: \n\n Develop customized content, including proposal (RFI/RFP) presentations, product demos and Word/Excel proposals, to support the presales process. \n Create engaging content that clearly communicates the value proposition of SHL’s solutions and services \n Collaborate with Solution Architects and sales teams to ensure content aligns with client requirements, business goals, strategy \n\n Collaboration with Sales and Technical (CoE) Teams: \n\n Work closely with Centre of Excellence to understand client technical requirements and submission planning. \n Professional Services: be an expert on what products and services we deliver. Ensure all aspects of client engagements can be delivered and set realistic timelines \n Product: Allowing a solid understanding of our solutions and stay appraised of digital roadmap and releases \n\nCustomer Engagement\n\n Support sales teams getting ready for client meetings, demos, and presentations \n Help refine product positioning and messaging to resonate with the client’s industry and business context. \n\nContent Strategy And Development\n\n Develop and maintain a local library of reusable content, templates, and resources for presales presentations, proposals, and client demos. \n Continuously assess the effectiveness of content and iterate based on client feedback and sales outcomes. \n Stay up to date with industry trends, competitor content, and customer preferences to enhance content quality \n\n Required Skills and Qualifications: \n\n Qualification in Technology, Marketing, Communications, Business, or a related field \n Ideally 2-4 years of experience in a Presales or commercial operations preferably within a technology, SaaS or services industry. \n Strong writing, editing, and presentation skills with an ability to craft clear, persuasive, and engaging content. \n Experience with design tools (e.g., PowerPoint, Synthesia, Adobe, Canva). \n Strong communication and collaboration skills to work cross-functional teams. \n Ability to quickly understand customer needs and develop content that resonates with different audiences. \n Attention to detail and ability to manage multiple content development projects simultaneously. \n Utility player! You thrive in the unknown and enjoy wearing multiple hats \n\nDesirable\n\n Presales tools: Walnut, Custom Report Developer tools \n Marketing skills: Canva, Synthesia \n Contracting skills: Experience writing Statements of work \n Proposal skills: populating responses to RFPs, Loopio \n Technical skills: understanding of HR technology and workflows. Experience solutioning complex integrations. \n\nGet In Touch\n\nFind out how this one-off opportunity can help you to achieve your career goals by making an application to our knowledgeable Talent Acquisition team. Choose a new path with SHL. \n\n#PreSalesOperations #SHL #CareersAtSHL \n\nAbout Us\n\nWe unlock the possibilities of businesses through the power of people, science and technology.\nWe started this industry of people insight more than 40 years ago and continue to lead the market with powerhouse product launches, ground-breaking science and business transformation.\nWhen you inspire and transform people’s lives, you will experience the greatest business outcomes possible. SHL’s products insights, experiences, and services can help achieve growth at scale.\n\nWhat SHL Can Offer You\n\nDiversity, equity, inclusion and accessibility are key threads in the fabric of SHL’s business and culture (find out more about DEI and accessibility at SHL )\n\nEmployee benefits package that takes care of you and your family.\nSupport, coaching, and on-the-job development to achieve career success\nA fun and flexible workplace where you’ll be inspired to do your best work (find out more LifeAtSHL )\nThe ability to transform workplaces around the world for others.\n\nSHL is an equal opportunity employer. We support and encourage applications from a diverse range of candidates. We can, and do make adjustments to make sure our recruitment process is as inclusive as possible.\n\nHere and I have want them to give a test which is atleast  30 mins long',
 'I am new looking for new graduates in my sales team, suggest an 30 min long assessment',
 "For Marketing - Content Writer Position\n\nDepartment: Marketing\n\nLocation: Gurugram\n\nAbout Company\n\nShopClues.com is India's leading e-commerce platform that is focused on changing the shopping scenario of the country. We are the one-stop platform for everything from electronics to fashion to home & kitchen. The company visions to be the largest and most customer-centric e-commerce platform for India.\n\nShopClues.com has been operating out of Silicon Valley since February 2011 and has its headquarters in Gurugram. The Company launched its Beta version on 26th January 2012 and has been constantly evolving since then for the better.\n\nOur Culture\n\nWe are a team of enthusiastic and determined individuals, who believe in working together with lots of energy, bringing continuous innovations to the organization, and celebrating every bit of it. We provide equal opportunity to each individual and look forward to executing the best ideas.\n\nThe Typical Creative Process Involves\n\nDiscussing the campaign's core message and target audience\nBrainstorming visual and copy ideas with other members of the creative team\nVisualizing different forms of communication approaches for various marketing platforms like Website, Email, Social, etc. for ShopClues.\nGenerating Stories for Brands core blog, and other content-driven platforms.\nOverseeing the production phase till the final output.\nExperience in the publishing of Push Notification and unique Product Description.",
 'I want to hire a product manager with 3-4 years of work experience and expertise in SDLC, Jira and Confluence',
 'Suggest me an assessment for the JD below Job Description\n\n Find purpose in each day while contributing to a workplace revolution! SHL, People Science. People Answers. \n\nAre you a driven business professional eager to develop your career by contributing directly to business success? SHL is seeking a Finance & Operations Analyst to join our AMS team!\n\n The Finance & Operations Analyst  will provide insights, analysis, and guidance to commercial teams to drive informed outcomes. This role bridges the gap between finance & operations and the business, ensuring alignment with the organization’s strategic goals and delivering value-added advice to improve performance.\n\nAn excellent benefits package is offered in a culture where career development, with ongoing manager guidance, collaboration, flexibility, diversity and inclusivity are all intrinsic to our culture.\u202f There is a huge investment in SHL currently so there’s no better time to become a part of something transformational.\u202f Hybrid working is available.\n\nWhat You Will Be Doing\n\n Financial Reporting: Deliver accurate monthly management accounts, variance evaluation, and KPI insights to help data-driven decision-making. \n Budgeting & Forecasting: Assist in preparing budgets and forecasts, identifying financial risks, opportunities, and recommending strategic actions. \n Business Partnering: Act as the primary finance contact, collaborating with sales, marketing, and operations on pricing, investments, and business cases. \n Cost Management: Monitor and evaluate costs, ensuring budget alignment and identifying cost-saving opportunities without compromising service quality. \n Performance Insights: Track financial KPIs, providing actionable insights to enhance business performance and profitability. \n Process Improvement: Streamline financial processes, implement top practices, and guidance system enhancements for efficiency and accuracy. \n Ad-Hoc Analysis : Provide financial insights to assist business initiatives, projects, and outcomes. Assist senior finance team members with reporting, insight, and financial planning. \n\n What we are looking for from you: \n\n Experience in finance, accounting, business, or a related field. \n 1-2 years of experience in a financial, analytical, or commercial role. \n Experience in financial modeling, Excel, and accounting systems (e.g., SAP, Oracle, or similar). \n Knowledge of commercial operations and drivers of profitability. \n Strong analytical and critical thinking techniques with attention to detail. \n Excellent relationship-building and communication techniques, able to present financial data clearly to non-finance stakeholders. \n Proactive and self-motivated, with a collaborative approach to work. \n\nGet In Touch\n\nFind out how this one-off opportunity can help you to achieve your career goals by making an application to our knowledgeable and friendly Talent Acquisition team. Choose a new path with SHL.\n\n #CareersAtSHL #SHLHiringTalent #HybridRole # salesoperationsjobs #financeanalystjobs #salesjobs\n\nAbout Us\n\nWe unlock the possibilities of businesses through the power of people, science and technology.\nWe started this industry of people insight more than 40 years ago and continue to lead the market with powerhouse product launches, ground-breaking science and business transformation.\nWhen you inspire and transform people’s lives, you will experience the greatest business outcomes possible. SHL’s products insights, experiences, and services can help achieve growth at scale.\n\nWhat SHL Can Offer You\n\nDiversity, equity, inclusion and accessibility are key threads in the fabric of SHL’s business and culture (find out more about DEI and accessibility at SHL )\n\nEmployee benefits package that takes care of you and your family.\nSupport, coaching, and on-the-job development to achieve career success\nA fun and flexible workplace where you’ll be inspired to do your best work (find out more LifeAtSHL )\nThe ability to transform workplaces around the world for others.\n\nSHL is an equal opportunity employer. We support and encourage applications from a diverse range of candidates. We can, and do make adjustments to make sure our recruitment process is as inclusive as possible.',
 'I want to hire Customer support executives who are expert in English communication.  \nWe are looking for talented Customer Support specialists to join our Product operations team in India (Mumbai)\n\n\nMinna connects global banks and fintech with subscription businesses to give consumers self-serve subscription management in-app. Minna is a technology partner to top-tier financial institutions, fintech and subscription businesses, providing subscription management functionality for 50+ million banking and fintech customers across the United States, United Kingdom and Europe.\nMinna builds the infrastructure that links Subscription Merchants (such as Netflix, Spotify, Amazon) to leading Financial Institutions (Lloyds Bank, ING Belgium, Swedbank to name a few). This connection enables consumers to effortlessly manage their subscriptions by performing actions like canceling, pausing, or changing their plans.\n\n\nResponsibilities:\n\nEfficiently manage cancellations and monitor cancellation status for merchants\nInitiate and execute workflows for cancellations at various stages of the cancellation journey with merchants\nProvide friendly and efficient customer service support via chat, calls, emails, and other channels\nFamiliarity with Minna’s Merchant Registry and classifications for merchants, services, and categories\nProficiency in understanding subscription terms and pulling relevant information from internal systems to support Account Management, Sales, and other queries\nConduct outbound calls to customers for subscription management and issue resolution\nHandle incoming queries from customers and merchants, ensuring timely resolution and escalation when necessary\nCollaborate with cross-functional teams to improve processes and enhance the customer experience\nMaintain accurate records and documentation of customer interactions and issue resolutions\n\n\nBased\n\nThis role is based in Mumbai and will require daily commute.\n\n\nRequirements:\n\nFluent in English with a minimum of 2-3 years of work experience in an International Call Center (US Voice Process or UK Voice Process)\nComfortable working full-time in English and willing to work in US or UK shifts, must be flexible with work timings.\nDemonstrated ability to deliver excellent customer service and resolve issues with good judgment\nStrong analytical abilities for troubleshooting and problem-solving\nAppreciation for routine tasks and ability to follow clear instructions\nComfortable multitasking to manage calls, emails, and chats simultaneously in an outbound calling process\nStrong communication skills, both verbal and written, with a friendly and professional tone\nAbility to adapt to a fast-paced and technologically advanced environment\nDetail-oriented with strong organizational skills and the ability to prioritize tasks effectively\n\n\nOur global benefits\n\n25 days holiday plus public holidays\nPrivate health insurance\nSubscription allowance\nFind more information about our benefits here\nMinna is an equal opportunities employer and does not discriminate on the basis of race, nationality, ethnicity, skin colour, religion, disability or sexual orientation. We celebrate and embrace a diverse workforce and are committed to building a team that represents a variety of backgrounds, perspectives and skills.']

In [68]:
len(results)

10

In [73]:
query_url_mapping={}
for result in results:
    query=result['query']
    # print(query)
    for recommend in result['recommendations']:
        if query not in query_url_mapping:
            query_url_mapping[query] = []
        query_url_mapping[query].append(recommend['url'])

In [74]:
query_url_mapping

{'Looking to hire mid-level professionals who are proficient in Python, SQL and Java Script. Need an assessment package that can test all skills with max duration of 60 minutes.': ['https://www.shl.com/products/product-catalog/view/python-new/',
  'https://www.shl.com/products/product-catalog/view/javascript-new/',
  'https://www.shl.com/products/product-catalog/view/sql-new/',
  'https://www.shl.com/products/product-catalog/view/automata-sql-new/',
  'https://www.shl.com/products/product-catalog/view/programming-concepts/',
  'https://www.shl.com/products/product-catalog/view/automata-front-end/',
  'https://www.shl.com/products/product-catalog/view/sql-server-integration-services-ssis-new/',
  'https://www.shl.com/products/product-catalog/view/python-new/',
  'https://www.shl.com/products/product-catalog/view/javascript-new/',
  'https://www.shl.com/products/product-catalog/view/sql-new/',
  'https://www.shl.com/products/product-catalog/view/automata-sql-new/',
  'https://www.shl.com/products/product-catalog/view/programming-concepts/',
  'https://www.shl.com/products/product-catalog/view/automata-front-end/',
  'https://www.shl.com/products/product-catalog/view/sql-server-integration-services-ssis-new/'],
 'Job Description\n\n Join a community that is shaping the future of work! \n\n SHL, People Science. People Answers. \n\nAre you an AI enthusiastwith visionary thinking to conceptualize AI-based products? Are you looking to apply these skills in an environment where teamwork and collaboration are key to developing our digital product experiences? We are seeking a Research Engineer to join our team to deliver robust AI/ML models. You will closely work with the product team to spot opportunities to use AI in the current product stack and influence the product roadmap by incorporating AI-led features/products.\n\nAn excellent benefits package is offered in a culture where career development, with ongoing manager guidance, collaboration, flexibility, diversity, and inclusivity are all intrinsic to our culture.\u202f There is a huge investment in SHL currently so there’s no better time to become a part of something transformational.\n\nWhat You Will Be Doing\n\n Develop and experiment with machine learning models like NLP, computer vision etc. \n Prototype and fine-tune generative AI models for text, image, speech, and video generation. \n Implement emerging LLM technologies and monitoring tools. \n Manage the entire AI/ML lifecycle from research to deployment and maintenance. \n Optimize models for scalability, efficiency, and performance. \n Collaborate with ML engineers for solution delivery and propose AI-driven enhancements. \n Contribute to research, documentation, and publications with AI/ML advancements. \n\nEssential\n\nWhat we are looking for from you:\n\n Relevant experience in AI/ML - NLP, speech processing, and computer vision. \n Proficiency in Python and ML frameworks such as TensorFlow, PyTorch, & OpenAI APIs. \n Good knowledge of ML theory deep learning, and statistical modeling. \n\nDesirable\n\n Familiarity with Generative AI (LLMs & RAG). \n Experience in prototyping and deploying AI. \n Agile and proactive thinking. \n\nGet In Touch\n\nFind out how this one-off opportunity can help you to achieve your career goals by making an application to our knowledgeable and friendly Talent Acquisition team. Choose a new path with SHL.\n\n #CareersAtSHL #SHLHiringTalent \n\n#AIJobs #ResearchJobs #MLJobs\n\n#CareerOpportunities #JobOpportunities \n\nAbout Us\n\n We unlock the possibilities of businesses through the power of people, science and technology. \n We started this industry of people insight more than 40 years ago and continue to lead the market with powerhouse product launches, ground-breaking science and business transformation. \n When you inspire and transform people’s lives, you will experience the greatest business outcomes possible. SHL’s products insights, experiences, and services can help achieve growth at scale. \n\nWhat SHL Can Offer You\n\n Diversity, equity, inclusion and accessibility are key threads in the fabric of SHL’s business and culture (find out more about DEI and accessibility at SHL ) \n Employee benefits package that takes care of you and your family. \n Support, coaching, and on-the-job development to achieve career success \n A fun and flexible workplace where you’ll be inspired to do your best work (find out more LifeAtSHL ) \n The ability to transform workplaces around the world for others. \n\nSHL is an equal opportunity employer. We support and encourage applications from a diverse range of candidates. We can, and do make adjustments to make sure our recruitment process is as inclusive as possible.\n\nCan you recommend some assessment that can help me screen applications. Time limit is less than 30 minutes': ['https://www.shl.com/products/product-catalog/view/ai-skills/',
  'https://www.shl.com/products/product-catalog/view/data-science-new/',
  'https://www.shl.com/products/product-catalog/view/programming-concepts/',
  'https://www.shl.com/products/product-catalog/view/agile-software-development/',
  'https://www.shl.com/products/product-catalog/view/dojo-new/',
  'https://www.shl.com/products/product-catalog/view/conversational-multichat-simulation/',
  'https://www.shl.com/products/product-catalog/view/remoteworkq/'],
 'I am hiring for an analyst and wants applications to screen using Cognitive and personality tests, what options are available within 45 mins.': ['https://www.shl.com/products/product-catalog/view/occupational-personality-questionnaire-opq32r/',
  'https://www.shl.com/products/product-catalog/view/dependability-and-safety-instrument-dsi/',
  'https://www.shl.com/products/product-catalog/view/remoteworkq/',
  'https://www.shl.com/products/product-catalog/view/ai-skills/',
  'https://www.shl.com/products/product-catalog/view/global-skills-assessment/',
  'https://www.shl.com/products/product-catalog/view/entry-level-technical-support-solution/',
  'https://www.shl.com/products/product-catalog/view/shl-verify-interactive-g/',
  'https://www.shl.com/products/product-catalog/view/universal-competency-framework-profiler-cards-44/'],
 'I have a JD Job Description\n\n People Science. People Answers  !\n\nDo you love contributing to commercial growth and success? Join as a Presales Specialist! In this role, you’ll support the Presales function and commercial teams by building custom client demos, developing RFP responses, writing high quality Statements of Work, ensuring our deals are appropriately scoped and priced.\n\nAn excellent benefits package is offered in a culture where career development, with ongoing manager guidance, collaboration, flexibility, diversity and inclusivity are all intrinsic to our culture. There is a huge investment in SHL currently so there ’ s no better time to become a part of something transformational. Hybrid working is available\n\nThis role is based in the US. Candidates must be eligible to work in the US without sponsorship. SHL does not offer visa sponsorship.\n\nThe Presales Specialist is responsible for creating, curating, and presenting compelling content to support the Solution Architects and Sales team during the presales phase. This includes:\n\n Building custom demos \n Responding to RFPs \n Maintaining knowledge of SHL commercial offerings, pricing, and platforms. \n Scoping support for commercial opportunities \n Creating compelling proposals \n Presenting Solution Vision to Customers \n Ensuring successful handover from pre-sales to delivery teams \n Maintaining domain expertise in the Talent Intelligence and HCM space \n\nKey Responsibilities\n\n Content Creation and Customization: \n\n Develop customized content, including proposal (RFI/RFP) presentations, product demos and Word/Excel proposals, to support the presales process. \n Create engaging content that clearly communicates the value proposition of SHL’s solutions and services \n Collaborate with Solution Architects and sales teams to ensure content aligns with client requirements, business goals, strategy \n\n Collaboration with Sales and Technical (CoE) Teams: \n\n Work closely with Centre of Excellence to understand client technical requirements and submission planning. \n Professional Services: be an expert on what products and services we deliver. Ensure all aspects of client engagements can be delivered and set realistic timelines \n Product: Allowing a solid understanding of our solutions and stay appraised of digital roadmap and releases \n\nCustomer Engagement\n\n Support sales teams getting ready for client meetings, demos, and presentations \n Help refine product positioning and messaging to resonate with the client’s industry and business context. \n\nContent Strategy And Development\n\n Develop and maintain a local library of reusable content, templates, and resources for presales presentations, proposals, and client demos. \n Continuously assess the effectiveness of content and iterate based on client feedback and sales outcomes. \n Stay up to date with industry trends, competitor content, and customer preferences to enhance content quality \n\n Required Skills and Qualifications: \n\n Qualification in Technology, Marketing, Communications, Business, or a related field \n Ideally 2-4 years of experience in a Presales or commercial operations preferably within a technology, SaaS or services industry. \n Strong writing, editing, and presentation skills with an ability to craft clear, persuasive, and engaging content. \n Experience with design tools (e.g., PowerPoint, Synthesia, Adobe, Canva). \n Strong communication and collaboration skills to work cross-functional teams. \n Ability to quickly understand customer needs and develop content that resonates with different audiences. \n Attention to detail and ability to manage multiple content development projects simultaneously. \n Utility player! You thrive in the unknown and enjoy wearing multiple hats \n\nDesirable\n\n Presales tools: Walnut, Custom Report Developer tools \n Marketing skills: Canva, Synthesia \n Contracting skills: Experience writing Statements of work \n Proposal skills: populating responses to RFPs, Loopio \n Technical skills: understanding of HR technology and workflows. Experience solutioning complex integrations. \n\nGet In Touch\n\nFind out how this one-off opportunity can help you to achieve your career goals by making an application to our knowledgeable Talent Acquisition team. Choose a new path with SHL. \n\n#PreSalesOperations #SHL #CareersAtSHL \n\nAbout Us\n\nWe unlock the possibilities of businesses through the power of people, science and technology.\nWe started this industry of people insight more than 40 years ago and continue to lead the market with powerhouse product launches, ground-breaking science and business transformation.\nWhen you inspire and transform people’s lives, you will experience the greatest business outcomes possible. SHL’s products insights, experiences, and services can help achieve growth at scale.\n\nWhat SHL Can Offer You\n\nDiversity, equity, inclusion and accessibility are key threads in the fabric of SHL’s business and culture (find out more about DEI and accessibility at SHL )\n\nEmployee benefits package that takes care of you and your family.\nSupport, coaching, and on-the-job development to achieve career success\nA fun and flexible workplace where you’ll be inspired to do your best work (find out more LifeAtSHL )\nThe ability to transform workplaces around the world for others.\n\nSHL is an equal opportunity employer. We support and encourage applications from a diverse range of candidates. We can, and do make adjustments to make sure our recruitment process is as inclusive as possible.\n\nHere and I have want them to give a test which is atleast  30 mins long': ['https://www.shl.com/products/product-catalog/view/entry-level-sales-solution/',
  'https://www.shl.com/products/product-catalog/view/interpersonal-communications/',
  'https://www.shl.com/products/product-catalog/view/remoteworkq/',
  'https://www.shl.com/products/product-catalog/view/ai-skills/',
  'https://www.shl.com/products/product-catalog/view/proofreading-v1/',
  'https://www.shl.com/products/product-catalog/view/smart-interview-on-demand/',
  'https://www.shl.com/products/product-catalog/view/automata-front-end/'],
 'I am new looking for new graduates in my sales team, suggest an 30 min long assessment': ['https://www.shl.com/products/product-catalog/view/entry-level-sales-solution/',
  'https://www.shl.com/products/product-catalog/view/sales-transformation-report-individual-contributor/',
  'https://www.shl.com/products/product-catalog/view/retail-sales-and-service-simulation/',
  'https://www.shl.com/products/product-catalog/view/sales-interview-guide/',
  'https://www.shl.com/products/product-catalog/view/salesforce-development-new/',
  'https://www.shl.com/products/product-catalog/view/conversational-multichat-simulation/',
  'https://www.shl.com/products/product-catalog/view/automata-front-end/',
  'https://www.shl.com/products/product-catalog/view/accounts-receivable-simulation-new/',
  'https://www.shl.com/products/product-catalog/view/graduate-scenarios/',
  'https://www.shl.com/products/product-catalog/view/shl-verify-interactive-deductive-reasoning/'],
 "For Marketing - Content Writer Position\n\nDepartment: Marketing\n\nLocation: Gurugram\n\nAbout Company\n\nShopClues.com is India's leading e-commerce platform that is focused on changing the shopping scenario of the country. We are the one-stop platform for everything from electronics to fashion to home & kitchen. The company visions to be the largest and most customer-centric e-commerce platform for India.\n\nShopClues.com has been operating out of Silicon Valley since February 2011 and has its headquarters in Gurugram. The Company launched its Beta version on 26th January 2012 and has been constantly evolving since then for the better.\n\nOur Culture\n\nWe are a team of enthusiastic and determined individuals, who believe in working together with lots of energy, bringing continuous innovations to the organization, and celebrating every bit of it. We provide equal opportunity to each individual and look forward to executing the best ideas.\n\nThe Typical Creative Process Involves\n\nDiscussing the campaign's core message and target audience\nBrainstorming visual and copy ideas with other members of the creative team\nVisualizing different forms of communication approaches for various marketing platforms like Website, Email, Social, etc. for ShopClues.\nGenerating Stories for Brands core blog, and other content-driven platforms.\nOverseeing the production phase till the final output.\nExperience in the publishing of Push Notification and unique Product Description.": ['https://www.shl.com/products/product-catalog/view/marketing-new/',
  'https://www.shl.com/products/product-catalog/view/search-engine-optimization-new/',
  'https://www.shl.com/products/product-catalog/view/proofreading-v1/',
  'https://www.shl.com/products/product-catalog/view/conversational-multichat-simulation/',
  'https://www.shl.com/products/product-catalog/view/business-communication-adaptive/',
  'https://www.shl.com/products/product-catalog/view/entry-level-customer-serv-retail-and-contact-center/'],
 'Suggest me an assessment for the JD below Job Description\n\n Find purpose in each day while contributing to a workplace revolution! SHL, People Science. People Answers. \n\nAre you a driven business professional eager to develop your career by contributing directly to business success? SHL is seeking a Finance & Operations Analyst to join our AMS team!\n\n The Finance & Operations Analyst  will provide insights, analysis, and guidance to commercial teams to drive informed outcomes. This role bridges the gap between finance & operations and the business, ensuring alignment with the organization’s strategic goals and delivering value-added advice to improve performance.\n\nAn excellent benefits package is offered in a culture where career development, with ongoing manager guidance, collaboration, flexibility, diversity and inclusivity are all intrinsic to our culture.\u202f There is a huge investment in SHL currently so there’s no better time to become a part of something transformational.\u202f Hybrid working is available.\n\nWhat You Will Be Doing\n\n Financial Reporting: Deliver accurate monthly management accounts, variance evaluation, and KPI insights to help data-driven decision-making. \n Budgeting & Forecasting: Assist in preparing budgets and forecasts, identifying financial risks, opportunities, and recommending strategic actions. \n Business Partnering: Act as the primary finance contact, collaborating with sales, marketing, and operations on pricing, investments, and business cases. \n Cost Management: Monitor and evaluate costs, ensuring budget alignment and identifying cost-saving opportunities without compromising service quality. \n Performance Insights: Track financial KPIs, providing actionable insights to enhance business performance and profitability. \n Process Improvement: Streamline financial processes, implement top practices, and guidance system enhancements for efficiency and accuracy. \n Ad-Hoc Analysis : Provide financial insights to assist business initiatives, projects, and outcomes. Assist senior finance team members with reporting, insight, and financial planning. \n\n What we are looking for from you: \n\n Experience in finance, accounting, business, or a related field. \n 1-2 years of experience in a financial, analytical, or commercial role. \n Experience in financial modeling, Excel, and accounting systems (e.g., SAP, Oracle, or similar). \n Knowledge of commercial operations and drivers of profitability. \n Strong analytical and critical thinking techniques with attention to detail. \n Excellent relationship-building and communication techniques, able to present financial data clearly to non-finance stakeholders. \n Proactive and self-motivated, with a collaborative approach to work. \n\nGet In Touch\n\nFind out how this one-off opportunity can help you to achieve your career goals by making an application to our knowledgeable and friendly Talent Acquisition team. Choose a new path with SHL.\n\n #CareersAtSHL #SHLHiringTalent #HybridRole # salesoperationsjobs #financeanalystjobs #salesjobs\n\nAbout Us\n\nWe unlock the possibilities of businesses through the power of people, science and technology.\nWe started this industry of people insight more than 40 years ago and continue to lead the market with powerhouse product launches, ground-breaking science and business transformation.\nWhen you inspire and transform people’s lives, you will experience the greatest business outcomes possible. SHL’s products insights, experiences, and services can help achieve growth at scale.\n\nWhat SHL Can Offer You\n\nDiversity, equity, inclusion and accessibility are key threads in the fabric of SHL’s business and culture (find out more about DEI and accessibility at SHL )\n\nEmployee benefits package that takes care of you and your family.\nSupport, coaching, and on-the-job development to achieve career success\nA fun and flexible workplace where you’ll be inspired to do your best work (find out more LifeAtSHL )\nThe ability to transform workplaces around the world for others.\n\nSHL is an equal opportunity employer. We support and encourage applications from a diverse range of candidates. We can, and do make adjustments to make sure our recruitment process is as inclusive as possible.': ['https://www.shl.com/products/product-catalog/view/financial-accounting-new/',
  'https://www.shl.com/products/product-catalog/view/shl-verify-interactive-numerical-calculation/',
  'https://www.shl.com/products/product-catalog/view/financial-and-banking-services-new/',

In [76]:
output=[]
for query,urls in query_url_mapping.items():
    for url in urls:
        output.append(pd.DataFrame({"Query":[query],'Assessment_url':[url]}))

In [79]:
output=pd.concat(output).drop_duplicates()

In [80]:
output.to_csv('arnav_kapoor.csv',index=False)